In [1]:
import pandas as pd

# Read in dataset from data preprocessing
df = pd.read_csv("clean_matches.csv")
df

,match_id,date,ground,home team,home score,away team,away score,goalscorer(s)
0,1,2006-07-26,Murrayfield,Hearts,3,Siroki Brijeg,0,"['Branimir Arnic (og)', 'Ibrahim Tall', 'Roman..."
1,2,2008-01-01,Old Trafford,Man United,1,Birmingham,0,['Carlos Tevez']
2,3,2008-11-01,Old Trafford,Man United,4,Hull,3,"['Cristiano Ronaldo (x2)', 'Nemanja Vidic', 'M..."
3,4,2008-11-19,Windsor Park,NI,0,Hungary,2,"['Sandor Torghelle', 'Zoltan Gera']"
4,5,2010-10-30,Camp Nou,Barcelona,5,Sevilla,0,"['Lionel Messi (x2)', 'David Villa (x2)', 'Dan..."
5,6,2012-02-29,Windsor Park,NI,0,Norway,3,"['Harvard Nordtveit', 'Tarik Elyounoussi', 'Es..."
6,7,2012-08-04,Portman Road,Ipswich,3,West Ham,1,"['Michael Chopra', 'Luke Chambers', 'Jason Sco..."
7,8,2012-08-08,Old Trafford,Brazil,3,South Korea,0,"['Romulo', 'Leandro Damiao (x2)']"
8,9,2016-01-19,Villa Park,Aston Villa,2,Wycombe,0,"['Cieran Clark', 'Idrissa Gana Gueye']"
9,10,2016-03-28,Windsor Park,NI,1,Slovenia,0,['Conor Washington']
10,11,2017-05-11,Old Trafford,Man United,1,Celta Vigo,1,"['Marounne Fellaini', 'Facundo Roncaglia']"
11,12,2017-09-30,One Call Stadium,Mansfield,3,Notts County,1,"['Danny Rose (x2)', 'Richard Duffy (og)', 'Car..."
12,13,2017-10-28,Wanda Metropolitano,Atletico Madrid,1,Villareal,1,"['Angel Correa', 'Carlos Bacca']"
13,14,2017-11-25,Meadow Lane,Notts County,2,Colchester,1,"['Shola Ameobi', 'Ryan Yates', 'Sanmu Odelusi']"
14,15,2017-12-14,Old Trafford,Man United,1,Bournemouth,0,['Romelu Lukaku']
15,16,2018-07-28,Panasonic Stadium,Gamba Osaka,1,Kashima Antlers,1,"['Koki Yonekura', 'Koki Machido']"
16,17,2018-08-11,City Ground,Nottingham Forest,1,Reading,0,['Hilal Soudani']
17,18,2019-10-10,Old Trafford,Man United,3,Brighton,1,"['Andreas Pereira', 'Scott McTominay', 'Lewis ..."
18,19,2019-12-01,Old Trafford,Man United,2,Aston Villa,2,"['Jack Grealish', 'Tom Heaton (og)', 'Victor L..."
19,20,2019-12-14,King Power Stadium,Leicester,1,Norwich,1,"['Teemu Pukki', 'Tim Krul (og)']"
20,21,2020-02-24,Old Trafford,Man United,3,Watford,0,"['Bruno Fernandes', 'Antony Martial', 'Mason G..."
21,22,2021-12-11,Carrow Road,Norwich,0,Man United,1,['Cristiano Ronaldo']
22,23,2022-02-05,Molineax,Wolves,0,Norwich,1,['Kenny McLean']
23,24,2022-04-30,Villa Park,Aston Villa,2,Norwich,0,"['Ollie Watkins', 'Danny Ings']"
24,25,2022-05-15,Molineax,Wolves,1,Norwich,1,"['Teemu Pukki', 'Rayan Ait-Nouri']"
25,26,2022-11-11,Old Trafford,Man United,4,Aston Villa,2,"['Ollie Watkins', 'Antony Martial', 'Diogo Dal..."
26,27,2023-04-29,Hawthorns,West Brown,2,Norwich,1,"['Josh Sargent', 'Connor Townsend', 'Jed Walla..."
27,28,2023-09-03,Emirates Stadium,Arsenal,3,Man United,1,"['Marcus Rashford', 'Martin Odegaard', 'Declan..."
28,29,2024-02-11,Olympic Stadium,West Ham,0,Arsenal,6,"['William Saliba', 'Bakayo Saka (x2)', 'Gabrie..."
29,30,2024-04-01,Cledara Abbey Stadium,Cambridge,3,Wigan,1,"['Gassan Ahadme (x2)', 'Danny Andrew', 'Martia..."
30,31,2024-04-04,Stamford Bridge,Chelsea,4,Man United,3,"['Connor Gallagher', 'Cole Palmer (x3)', 'Alej..."
31,32,2024-04-23,Cledara Abbey Stadium,Cambridge,1,Wycombe,1,"['Gassan Ahadme', 'Luke Leahy']"
32,33,2024-08-17,Cledara Abbey Stadium,Cambridge,0,Crawley,1,['Ade Adeyamo']
33,34,2024-09-24,Stamford Bridge,Chelsea,5,Barrow,0,"['Christopher Nkunku (x3)', 'Pedro Neto', 'Pau..."
34,35,2024-10-26,Cledara Abbey Stadium,Cambridge,1,Burton,0,['Jordan Cousins']
35,36,2024-11-26,Cledara Abbey Stadium,Cambridge,1,Bolton,1,"['Aaron Collins', 'Sulley Kaikai']"
36,37,2025-01-25,Cledara Abbey Stadium,Cambridge,3,Mansfield,2,"['Michael Morrison', 'Josh Stokes', 'Ryan Loft..."
37,38,2025-03-04,Cledara Abbey Stadium,Cambridge,0,Stevenage,1,['Jamie Reid']
38,39,2025-03-15,Cledara Abbey Stadium,Cambridge,0,Peterborough,1,['Tayo Edun']
39,40,2025-04-21,Cledara Abbey Stadium,Cambridge,1,Leyton Orient,2,"['Josh Stokes', 'Charlie Kelman', 'Jamie Donley']"
40,41,2025-08-02,Cledara Abbey Stadium,Cambridge,1,Cheltenham,0,['Louis Appere']
41,42,2025-08-30,Cledara Abbey Stadium,Cambridge,2,Newport,0,"['Kell Watts', 'James Brophy']"
42,43,2025-10-25,Old Trafford,Man United,4,Brighton,2,"['Matheus Cunha', 'Casemiro', 'Bryan Mbeumo (x..."
43,44,2025-12-15,Old Trafford,Man United,4,Bournemouth,4,"['Amad Diallo', 'Antoine Semenyo', 'Casemiro',..."
44,45,2026-03-21,Cledara Abbey Stadium,Cambridge,1,Salford,0,['James Gibbons']
45,46,2026-04-02,Cledara Abbey Stadium,Cambridge,1,Swindon,1,"['Ben Knight', 'Joel McGregor']"

In [2]:
# Function that builds the search query that will be input to Google
import calendar

def build_search_query(match):                              # Match will be row from the dataset
    # Set up variables that will be used in the string for search query
    home_team = match["home team"]
    away_team = match["away team"]
    month = calendar.month_name[int(match["date"][5:7])]    # Calendar converts the numbers 1-12 to the corresponding months January-December
    year = match["date"][0:4]
    return f"{home_team} vs {away_team} in {month} {year}"  # Return the search query in an f-string

In [3]:
# Test function from previous cell
build_search_query(df.iloc[44])

'Cambridge vs Salford in March 2026'

In [4]:
# Add the seach query as a column in the database
df["search query"] = df.apply(build_search_query, axis=1)
df

,match_id,date,ground,home team,home score,away team,away score,goalscorer(s),search query
0,1,2006-07-26,Murrayfield,Hearts,3,Siroki Brijeg,0,"['Branimir Arnic (og)', 'Ibrahim Tall', 'Roman...",Hearts vs Siroki Brijeg in July 2006
1,2,2008-01-01,Old Trafford,Man United,1,Birmingham,0,['Carlos Tevez'],Man United vs Birmingham in January 2008
2,3,2008-11-01,Old Trafford,Man United,4,Hull,3,"['Cristiano Ronaldo (x2)', 'Nemanja Vidic', 'M...",Man United vs Hull in November 2008
3,4,2008-11-19,Windsor Park,NI,0,Hungary,2,"['Sandor Torghelle', 'Zoltan Gera']",NI vs Hungary in November 2008
4,5,2010-10-30,Camp Nou,Barcelona,5,Sevilla,0,"['Lionel Messi (x2)', 'David Villa (x2)', 'Dan...",Barcelona vs Sevilla in October 2010
5,6,2012-02-29,Windsor Park,NI,0,Norway,3,"['Harvard Nordtveit', 'Tarik Elyounoussi', 'Es...",NI vs Norway in February 2012
6,7,2012-08-04,Portman Road,Ipswich,3,West Ham,1,"['Michael Chopra', 'Luke Chambers', 'Jason Sco...",Ipswich vs West Ham in August 2012
7,8,2012-08-08,Old Trafford,Brazil,3,South Korea,0,"['Romulo', 'Leandro Damiao (x2)']",Brazil vs South Korea in August 2012
8,9,2016-01-19,Villa Park,Aston Villa,2,Wycombe,0,"['Cieran Clark', 'Idrissa Gana Gueye']",Aston Villa vs Wycombe in January 2016
9,10,2016-03-28,Windsor Park,NI,1,Slovenia,0,['Conor Washington'],NI vs Slovenia in March 2016
10,11,2017-05-11,Old Trafford,Man United,1,Celta Vigo,1,"['Marounne Fellaini', 'Facundo Roncaglia']",Man United vs Celta Vigo in May 2017
11,12,2017-09-30,One Call Stadium,Mansfield,3,Notts County,1,"['Danny Rose (x2)', 'Richard Duffy (og)', 'Car...",Mansfield vs Notts County in September 2017
12,13,2017-10-28,Wanda Metropolitano,Atletico Madrid,1,Villareal,1,"['Angel Correa', 'Carlos Bacca']",Atletico Madrid vs Villareal in October 2017
13,14,2017-11-25,Meadow Lane,Notts County,2,Colchester,1,"['Shola Ameobi', 'Ryan Yates', 'Sanmu Odelusi']",Notts County vs Colchester in November 2017
14,15,2017-12-14,Old Trafford,Man United,1,Bournemouth,0,['Romelu Lukaku'],Man United vs Bournemouth in December 2017
15,16,2018-07-28,Panasonic Stadium,Gamba Osaka,1,Kashima Antlers,1,"['Koki Yonekura', 'Koki Machido']",Gamba Osaka vs Kashima Antlers in July 2018
16,17,2018-08-11,City Ground,Nottingham Forest,1,Reading,0,['Hilal Soudani'],Nottingham Forest vs Reading in August 2018
17,18,2019-10-10,Old Trafford,Man United,3,Brighton,1,"['Andreas Pereira', 'Scott McTominay', 'Lewis ...",Man United vs Brighton in October 2019
18,19,2019-12-01,Old Trafford,Man United,2,Aston Villa,2,"['Jack Grealish', 'Tom Heaton (og)', 'Victor L...",Man United vs Aston Villa in December 2019
19,20,2019-12-14,King Power Stadium,Leicester,1,Norwich,1,"['Teemu Pukki', 'Tim Krul (og)']",Leicester vs Norwich in December 2019
20,21,2020-02-24,Old Trafford,Man United,3,Watford,0,"['Bruno Fernandes', 'Antony Martial', 'Mason G...",Man United vs Watford in February 2020
21,22,2021-12-11,Carrow Road,Norwich,0,Man United,1,['Cristiano Ronaldo'],Norwich vs Man United in December 2021
22,23,2022-02-05,Molineax,Wolves,0,Norwich,1,['Kenny McLean'],Wolves vs Norwich in February 2022
23,24,2022-04-30,Villa Park,Aston Villa,2,Norwich,0,"['Ollie Watkins', 'Danny Ings']",Aston Villa vs Norwich in April 2022
24,25,2022-05-15,Molineax,Wolves,1,Norwich,1,"['Teemu Pukki', 'Rayan Ait-Nouri']",Wolves vs Norwich in May 2022
25,26,2022-11-11,Old Trafford,Man United,4,Aston Villa,2,"['Ollie Watkins', 'Antony Martial', 'Diogo Dal...",Man United vs Aston Villa in November 2022
26,27,2023-04-29,Hawthorns,West Brown,2,Norwich,1,"['Josh Sargent', 'Connor Townsend', 'Jed Walla...",West Brown vs Norwich in April 2023
27,28,2023-09-03,Emirates Stadium,Arsenal,3,Man United,1,"['Marcus Rashford', 'Martin Odegaard', 'Declan...",Arsenal vs Man United in September 2023
28,29,2024-02-11,Olympic Stadium,West Ham,0,Arsenal,6,"['William Saliba', 'Bakayo Saka (x2)', 'Gabrie...",West Ham vs Arsenal in February 2024
29,30,2024-04-01,Cledara Abbey Stadium,Cambridge,3,Wigan,1,"['Gassan Ahadme (x2)', 'Danny Andrew', 'Martia...",Cambridge vs Wigan in April 2024
30,31,2024-04-04,Stamford Bridge,Chelsea,4,Man United,3,"['Connor Gallagher', 'Cole Palmer (x3)', 'Alej...",Chelsea vs Man United in April 2024
31,32,2024-04-23,Cledara Abbey Stadium,Cambridge,1,Wycombe,1,"['Gassan Ahadme', 'Luke Leahy']",Cambridge vs Wycombe in April 2024
32,33,2024-08-17,Cledara Abbey Stadium,Cambridge,0,Crawley,1,['Ade Adeyamo'],Cambridge vs Crawley in August 2024
33,34,2024-09-24,Stamford Bridge,Chelsea,5,Barrow,0,"['Christopher Nkunku (x3)', 'Pedro Neto', 'Pau...",Chelsea vs Barrow in September 2024
34,35,2024-10-26,Cledara Abbey Stadium,Cambridge,1,Burton,0,['Jordan Cousins'],Cambridge vs Burton in October 2024
35,36,2024-11-26,Cledara Abbey Stadium,Cambridge,1,Bolton,1,"['Aaron Collins', 'Sulley Kaikai']",Cambridge vs Bolton in November 2024
36,37,2025-01-25,Cledara Abbey Stadium,Cambridge,3,Mansfield,2,"['Michael Morrison', 'Josh Stokes', 'Ryan Loft...",Cambridge vs Mansfield in January 2025
37,38,2025-03-04,Cledara Abbey Stadium,Cambridge,0,Stevenage,1,['Jamie Reid'],Cambridge vs Stevenage in March 2025
38,39,2025-03-15,Cledara Abbey Stadium,Cambridge,0,Peterborough,1,['Tayo Edun'],Cambridge vs Peterborough in March 2025
39,40,2025-04-21,Cledara Abbey Stadium,Cambridge,1,Leyton Orient,2,"['Josh Stokes', 'Charlie Kelman', 'Jamie Donley']",Cambridge vs Leyton Orient in April 2025
40,41,2025-08-02,Cledara Abbey Stadium,Cambridge,1,Cheltenham,0,['Louis Appere'],Cambridge vs Cheltenham in August 2025
41,42,2025-08-30,Cledara Abbey Stadium,Cambridge,2,Newport,0,"['Kell Watts', 'James Brophy']",Cambridge vs Newport in August 2025
42,43,2025-10-25,Old Trafford,Man United,4,Brighton,2,"['Matheus Cunha', 'Casemiro', 'Bryan Mbeumo (x...",Man United vs Brighton in October 2025
43,44,2025-12-15,Old Trafford,Man United,4,Bournemouth,4,"['Amad Diallo', 'Antoine Semenyo', 'Casemiro',...",Man United vs Bournemouth in December 2025
44,45,2026-03-21,Cledara Abbey Stadium,Cambridge,1,Salford,0,['James Gibbons'],Cambridge vs Salford in March 2026
45,46,2026-04-02,Cledara Abbey Stadium,Cambridge,1,Swindon,1,"['Ben Knight', 'Joel McGregor']",Cambridge vs Swindon in April 2026

In [ ]:
# API key needs to be kept private from public GITHUB repository
# Key stored in an .env file
# .env file listed within .gitignore
# This cell reads in the key and stores it with api_key

from dotenv import load_dotenv
import os

load_dotenv()
api_key = os.getenv("SERPAPI_KEY")

In [ ]:
# Function that performs the Google search query
# Uses SerpAPI

from serpapi import GoogleSearch

def get_urls(query):
    # Parameters for the Google search
    params = {
        "q": query,                     # The string to be query                
        "api_key": api_key,             # The SerpAPI key
        "num": 20                       # Max 20 links, but will naturally restrict to the first page of Google searches
    }

    search = GoogleSearch(params)       
    results = search.get_dict()         # Sends request to the API

    return [r["link"] for r in results.get("organic_results", [])]          # Extract links

# Test the function get_urls on the query generated for one of the matches
# Need to be careful about overusing this function: get 250 queries per month through free tier of SerpAPI

urls = get_urls("Man United vs Birmingham in January 2008")
urls

In [ ]:
# Access the urls variable from the previous cell without needing to send another query to SERPAPI
urls

In [5]:
# Able to redefine urls from above cell if I start a new session without needing to re-use a SERPAPI search
urls = ['https://www.youtube.com/watch?v=givC4ZvbqYc',
 'https://www.skysports.com/football/manchester-united-vs-birmingham-city/teams/94538',
 'https://www.transfermarkt.us/manchester-united_birmingham-city/index/spielbericht/81687',
 'https://www.manutd.com/en/videos/detail/man-utd-1-birmingham-city-0-extended-highlights-premier-league-2007-08',
 'https://www.statmuse.com/fc/ask/full-time-scores-of-man-u-vs-birmingham-in-premiere-league-match-in-2008',
 'http://news.bbc.co.uk/sport2/hi/football/eng_prem/7163892.stm',
 'https://www.premierleague.com/en/match/128642/manchester-united-vs-birmingham-city',
 'https://www.espn.ph/football/report/_/gameId/220076',
 'https://www.footballcritic.com/premier-league-manchester-united-fc-birmingham-city-fc/match-stats/42194']

In [6]:
# Test on one match before expanding to all to preserve SerpAPI queries
# Remove this cell before roll-out

df = df.iloc[[1]].copy()        # Make a copy of the second entry in a sample dataframe
df["article urls"] = [urls]     # Add a new column of the list of url strings
df

,match_id,date,ground,home team,home score,away team,away score,goalscorer(s),search query,article urls
1,2,2008-01-01,Old Trafford,Man United,1,Birmingham,0,['Carlos Tevez'],Man United vs Birmingham in January 2008,"[https://www.youtube.com/watch?v=givC4ZvbqYc, ..."

In [7]:
# Read text from an articles

import requests
from bs4 import BeautifulSoup
import re

def extract_article(url):
    html = requests.get(url).text               # Gets the raw HTML code of the webpage
    soup = BeautifulSoup(html, "html.parser")   # Parses the HTML code into paragraphs/heading/etc. by looking for <p>/<h1>/etc.

    paragraphs = [p.get_text() for p in soup.find_all("p")]     # Gets all paragraph text
    text = "\n".join(paragraphs)
    text = re.sub(r"\s+", " ", text)             # Find all chunks of whitespace and replace them with a single space. \s is any whitespace character. \s+ means more than one in a row
    return text.strip()

# Testing the function
extract_article("http://news.bbc.co.uk/sport2/hi/football/eng_prem/7163892.stm")

'Tevez\'s overhead kick and a Cristiano Ronaldo back-heel carved open the Blues defence and the Argentine calmly slotted home the winner on 25 minutes. Cameron Jerome was down injured then but Birmingham complaints were limited. Tevez, who went off late on with an ankle injury, also hit the woodwork twice while the Blues never gave up. Interview: Manchester United\'s Rio Ferdinand Interview: Birmingham boss Alex McLeish United manager Sir Alex Ferguson, sat in the stands to serve out his two-match touchline ban, made five changes to his starting line-up. Ronaldo partnered Tevez in the centre of attack with Wayne Rooney still absent with a virus and Ryan Giggs not even on the bench. Birmingham boss Alex McLeish - once a protege of Ferguson in their days together at Aberdeen - started with two up front. 606: DEBATE Have your say on Birmingham\'s narrow defeat at Old Trafford Jerome, partnering Gary O\'Connor, heeded the positive mantra of his boss and scorched a long-range effort over Tomasz Kuszczak\'s bar within 60 seconds. But Ronaldo soon set about making amends for his penalty miss in the defeat against West Ham on Saturday. After five minutes, he smuggled the ball through to the onrushing Patrice Evra who whipped the ball across the box from the left for Tevez to head against the foot of Maik Taylor\'s post from three yards. With Birmingham\'s midfield struggling to win possession, United\'s creative players bossed the tempo. The inevitable goal came when Tevez dropped deep to flip a pass over his head for Ronaldo, who controlled the ball and instantly back-heeled it into the path of the Argentine. Tevez, having pulled Liam Ridgewell and Rahdi Jaidi out of position, marched into the space and clinically passed the ball past Taylor into the corner of the goal. It was his eighth league goal this season and he celebrated in bizarre style - sucking on a pink baby\'s dummy. But 15th-placed Birmingham fought to find their way back into the game and, helped by the jitters of United\'s defence, carved out a couple of opportunities. Birmingham fought hard against a below-par Manchester United A Rio Ferdinand error and Fabrice Muamba\'s clever switch of play twice gave Gary McSheffrey time and space around the United box, yet he blazed shots high and wide. No personnel changes were made at half-time and neither did the pattern of play alter. Making his first United start since March, South Korea international Park Ji-sung raced to the byeline on 55 minutes to deliver a wicked cross onto the head of a leaping Ronaldo. The Portuguese headed downwards powerfully but a superb reaction stop from the feet of Taylor kept the ball out and Birmingham in the game. Minutes later Tevez crashed a shot against the post and a posse of Birmingham defenders bravely kept out Ronaldo\'s follow-up attempt. The one-way traffic continued with Tevez and Ronaldo orchestrating a 15-minute onslaught. Yet Birmingham brought on Mikael Forsell for Jerome and he swiftly helped remind United of the slenderness of their advantage as City enjoyed their best spell. First, he worked space for O\'Connor to place a decent effort on target, before shooting hard and low himself without success. With minutes remaining, Forsell found space but scuffed a shot wide with team-mates better placed to his right before United played the clock down for an important victory. Manchester United defender Rio Ferdinand:"It was good to get back to winning ways and take the three points. I\'m pleased with the clean sheet after we gave away two sloppy goals against West Ham. "It is disappointing not to get more goals, but it\'s the win that counts. "We weren\'t nervous at the end and we know in certain games we have to defend 1-0 leads. "It doesn\'t matter what Arsenal do. It we continue grinding out results then we know we have the players who can do the damage up front." Birmingham manager Alex McLeish:"They looked as if they would score every time they went up the pitch but I really felt we could nick something. "We had a really good start to the game and got into a number of good positions but just couldn\'t hit the target. "The United fans whistling for the final whistle was like music to my ears but we just couldn\'t make the breakthrough. "If we can add two or three players in the transfer window to help the players then that will be fantastic. The players know it\'s not a threat to them." Man Utd: Kuszczak, O\'Shea, Ferdinand, Vidic, Evra (Brown 84), Ronaldo, Anderson, Carrick, Nani, Park (Hargreaves 75), Tevez (Saha 71).Subs Not Used: Heaton, Pique. Booked: Brown. Goals: Tevez 25. Birmingham: Maik Taylor, Kelly, Jaidi, Ridgewell, Queudrue, McSheffrey (De Ridder 67), Nafti (Palacios 81), Muamba, Larsson, Jerome (Forssell 67), O\'Connor.Subs Not Used: Doyle, Parnaby. Booked: Ridgewell, Queudrue, Nafti, Palacios. Att: 75,459 Ref: Peter Walton (Northamptonshire). BBC Sport Player Rater man of the match: Manchester United\'s Carlos Tevez 8.15 Please note that you can still give the players marks out of 10 on BBC Sport\'s Player Rater after the match has finished.Player Rater Cameron Jerome was down injured then but Birmingham complaints were limited. Tevez, who went off late on with an ankle injury, also hit the woodwork twice while the Blues never gave up. Interview: Manchester United\'s Rio Ferdinand Interview: Birmingham boss Alex McLeish United manager Sir Alex Ferguson, sat in the stands to serve out his two-match touchline ban, made five changes to his starting line-up. Ronaldo partnered Tevez in the centre of attack with Wayne Rooney still absent with a virus and Ryan Giggs not even on the bench. Birmingham boss Alex McLeish - once a protege of Ferguson in their days together at Aberdeen - started with two up front. 606: DEBATE Have your say on Birmingham\'s narrow defeat at Old Trafford Jerome, partnering Gary O\'Connor, heeded the positive mantra of his boss and scorched a long-range effort over Tomasz Kuszczak\'s bar within 60 seconds. But Ronaldo soon set about making amends for his penalty miss in the defeat against West Ham on Saturday. After five minutes, he smuggled the ball through to the onrushing Patrice Evra who whipped the ball across the box from the left for Tevez to head against the foot of Maik Taylor\'s post from three yards. With Birmingham\'s midfield struggling to win possession, United\'s creative players bossed the tempo. The inevitable goal came when Tevez dropped deep to flip a pass over his head for Ronaldo, who controlled the ball and instantly back-heeled it into the path of the Argentine. Tevez, having pulled Liam Ridgewell and Rahdi Jaidi out of position, marched into the space and clinically passed the ball past Taylor into the corner of the goal. It was his eighth league goal this season and he celebrated in bizarre style - sucking on a pink baby\'s dummy. But 15th-placed Birmingham fought to find their way back into the game and, helped by the jitters of United\'s defence, carved out a couple of opportunities. Birmingham fought hard against a below-par Manchester United A Rio Ferdinand error and Fabrice Muamba\'s clever switch of play twice gave Gary McSheffrey time and space around the United box, yet he blazed shots high and wide. No personnel changes were made at half-time and neither did the pattern of play alter. Making his first United start since March, South Korea international Park Ji-sung raced to the byeline on 55 minutes to deliver a wicked cross onto the head of a leaping Ronaldo. The Portuguese headed downwards powerfully but a superb reaction stop from the feet of Taylor kept the ball out and Birmingham in the game. Minutes later Tevez crashed a shot against the post and a posse of Birmingham defenders bravely kept out Ronaldo\'s follow-up attempt. The one-way traffic continued with Tevez and Ronaldo orchestrating a 15-minute onslaught. Yet Birmingham brought on Mikael Forsell for Jerome and he swiftly helped remind United of the slenderness of their advantage as City enjoyed their best spell. First, he worked space for O\'Connor to place a decent effort on target, before shooting hard and low himself without success. With minutes remaining, Forsell found space but scuffed a shot wide with team-mates better placed to his right before United played the clock down for an important victory. Manchester United defender Rio Ferdinand:"It was good to get back to winning ways and take the three points. I\'m pleased with the clean sheet after we gave away two sloppy goals against West Ham. "It is disappointing not to get more goals, but it\'s the win that counts. "We weren\'t nervous at the end and we know in certain games we have to defend 1-0 leads. "It doesn\'t matter what Arsenal do. It we continue grinding out results then we know we have the players who can do the damage up front." Birmingham manager Alex McLeish:"They looked as if they would score every time they went up the pitch but I really felt we could nick something. "We had a really good start to the game and got into a number of good positions but just couldn\'t hit the target. "The United fans whistling for the final whistle was like music to my ears but we just couldn\'t make the breakthrough. "If we can add two or three players in the transfer window to help the players then that will be fantastic. The players know it\'s not a threat to them." Man Utd: Kuszczak, O\'Shea, Ferdinand, Vidic, Evra (Brown 84), Ronaldo, Anderson, Carrick, Nani, Park (Hargreaves 75), Tevez (Saha 71).Subs Not Used: Heaton, Pique. Booked: Brown. Goals: Tevez 25. Birmingham: Maik Taylor, Kelly, Jaidi, Ridgewell, Queudrue, McSheffrey (De Ridder 67), Nafti (Palacios 81), Muamba, Larsson, Jerome (Forssell 67), O\'Connor.Subs Not Used: Doyle, Parnaby. Booked: Ridgewell, Queudrue, Nafti, Palacios. Att: 75,459 Ref: Peter Walton (Northamptonshire). BBC Sport Player Rater man of the match: Manchester United\'s Carlos Tevez 8.15 Please note that you can still give the players marks out of 10 on BBC Sport\'s Player Rater after the match has finished.Player Rater Tevez, who went off late on with an ankle injury, also hit the woodwork twice while the Blues never gave up. Interview: Manchester United\'s Rio Ferdinand Interview: Birmingham boss Alex McLeish United manager Sir Alex Ferguson, sat in the stands to serve out his two-match touchline ban, made five changes to his starting line-up. Ronaldo partnered Tevez in the centre of attack with Wayne Rooney still absent with a virus and Ryan Giggs not even on the bench. Birmingham boss Alex McLeish - once a protege of Ferguson in their days together at Aberdeen - started with two up front. 606: DEBATE Have your say on Birmingham\'s narrow defeat at Old Trafford Jerome, partnering Gary O\'Connor, heeded the positive mantra of his boss and scorched a long-range effort over Tomasz Kuszczak\'s bar within 60 seconds. But Ronaldo soon set about making amends for his penalty miss in the defeat against West Ham on Saturday. After five minutes, he smuggled the ball through to the onrushing Patrice Evra who whipped the ball across the box from the left for Tevez to head against the foot of Maik Taylor\'s post from three yards. With Birmingham\'s midfield struggling to win possession, United\'s creative players bossed the tempo. The inevitable goal came when Tevez dropped deep to flip a pass over his head for Ronaldo, who controlled the ball and instantly back-heeled it into the path of the Argentine. Tevez, having pulled Liam Ridgewell and Rahdi Jaidi out of position, marched into the space and clinically passed the ball past Taylor into the corner of the goal. It was his eighth league goal this season and he celebrated in bizarre style - sucking on a pink baby\'s dummy. But 15th-placed Birmingham fought to find their way back into the game and, helped by the jitters of United\'s defence, carved out a couple of opportunities. Birmingham fought hard against a below-par Manchester United A Rio Ferdinand error and Fabrice Muamba\'s clever switch of play twice gave Gary McSheffrey time and space around the United box, yet he blazed shots high and wide. No personnel changes were made at half-time and neither did the pattern of play alter. Making his first United start since March, South Korea international Park Ji-sung raced to the byeline on 55 minutes to deliver a wicked cross onto the head of a leaping Ronaldo. The Portuguese headed downwards powerfully but a superb reaction stop from the feet of Taylor kept the ball out and Birmingham in the game. Minutes later Tevez crashed a shot against the post and a posse of Birmingham defenders bravely kept out Ronaldo\'s follow-up attempt. The one-way traffic continued with Tevez and Ronaldo orchestrating a 15-minute onslaught. Yet Birmingham brought on Mikael Forsell for Jerome and he swiftly helped remind United of the slenderness of their advantage as City enjoyed their best spell. First, he worked space for O\'Connor to place a decent effort on target, before shooting hard and low himself without success. With minutes remaining, Forsell found space but scuffed a shot wide with team-mates better placed to his right before United played the clock down for an important victory. Manchester United defender Rio Ferdinand:"It was good to get back to winning ways and take the three points. I\'m pleased with the clean sheet after we gave away two sloppy goals against West Ham. "It is disappointing not to get more goals, but it\'s the win that counts. "We weren\'t nervous at the end and we know in certain games we have to defend 1-0 leads. "It doesn\'t matter what Arsenal do. It we continue grinding out results then we know we have the players who can do the damage up front." Birmingham manager Alex McLeish:"They looked as if they would score every time they went up the pitch but I really felt we could nick something. "We had a really good start to the game and got into a number of good positions but just couldn\'t hit the target. "The United fans whistling for the final whistle was like music to my ears but we just couldn\'t make the breakthrough. "If we can add two or three players in the transfer window to help the players then that will be fantastic. The players know it\'s not a threat to them." Man Utd: Kuszczak, O\'Shea, Ferdinand, Vidic, Evra (Brown 84), Ronaldo, Anderson, Carrick, Nani, Park (Hargreaves 75), Tevez (Saha 71).Subs Not Used: Heaton, Pique. Booked: Brown. Goals: Tevez 25. Birmingham: Maik Taylor, Kelly, Jaidi, Ridgewell, Queudrue, McSheffrey (De Ridder 67), Nafti (Palacios 81), Muamba, Larsson, Jerome (Forssell 67), O\'Connor.Subs Not Used: Doyle, Parnaby. Booked: Ridgewell, Queudrue, Nafti, Palacios. Att: 75,459 Ref: Peter Walton (Northamptonshire). BBC Sport Player Rater man of the match: Manchester United\'s Carlos Tevez 8.15 Please note that you can still give the players marks out of 10 on BBC Sport\'s Player Rater after the match has finished.Player Rater Interview: Manchester United\'s Rio Ferdinand Interview: Birmingham boss Alex McLeish United manager Sir Alex Ferguson, sat in the stands to serve out his two-match touchline ban, made five changes to his starting line-up. Ronaldo partnered Tevez in the centre of attack with Wayne Rooney still absent with a virus and Ryan Giggs not even on the bench. Birmingham boss Alex McLeish - once a protege of Ferguson in their days together at Aberdeen - started with two up front. 606: DEBATE Have your say on Birmingham\'s narrow defeat at Old Trafford Jerome, partnering Gary O\'Connor, heeded the positive mantra of his boss and scorched a long-range effort over Tomasz Kuszczak\'s bar within 60 seconds. But Ronaldo soon set about making amends for his penalty miss in the defeat against West Ham on Saturday. After five minutes, he smuggled the ball through to the onrushing Patrice Evra who whipped the ball across the box from the left for Tevez to head against the foot of Maik Taylor\'s post from three yards. With Birmingham\'s midfield struggling to win possession, United\'s creative players bossed the tempo. The inevitable goal came when Tevez dropped deep to flip a pass over his head for Ronaldo, who controlled the ball and instantly back-heeled it into the path of the Argentine. Tevez, having pulled Liam Ridgewell and Rahdi Jaidi out of position, marched into the space and clinically passed the ball past Taylor into the corner of the goal. It was his eighth league goal this season and he celebrated in bizarre style - sucking on a pink baby\'s dummy. But 15th-placed Birmingham fought to find their way back into the game and, helped by the jitters of United\'s defence, carved out a couple of opportunities. Birmingham fought hard against a below-par Manchester United A Rio Ferdinand error and Fabrice Muamba\'s clever switch of play twice gave Gary McSheffrey time and space around the United box, yet he blazed shots high and wide. No personnel changes were made at half-time and neither did the pattern of play alter. Making his first United start since March, South Korea international Park Ji-sung raced to the byeline on 55 minutes to deliver a wicked cross onto the head of a leaping Ronaldo. The Portuguese headed downwards powerfully but a superb reaction stop from the feet of Taylor kept the ball out and Birmingham in the game. Minutes later Tevez crashed a shot against the post and a posse of Birmingham defenders bravely kept out Ronaldo\'s follow-up attempt. The one-way traffic continued with Tevez and Ronaldo orchestrating a 15-minute onslaught. Yet Birmingham brought on Mikael Forsell for Jerome and he swiftly helped remind United of the slenderness of their advantage as City enjoyed their best spell. First, he worked space for O\'Connor to place a decent effort on target, before shooting hard and low himself without success. With minutes remaining, Forsell found space but scuffed a shot wide with team-mates better placed to his right before United played the clock down for an important victory. Manchester United defender Rio Ferdinand:"It was good to get back to winning ways and take the three points. I\'m pleased with the clean sheet after we gave away two sloppy goals against West Ham. "It is disappointing not to get more goals, but it\'s the win that counts. "We weren\'t nervous at the end and we know in certain games we have to defend 1-0 leads. "It doesn\'t matter what Arsenal do. It we continue grinding out results then we know we have the players who can do the damage up front." Birmingham manager Alex McLeish:"They looked as if they would score every time they went up the pitch but I really felt we could nick something. "We had a really good start to the game and got into a number of good positions but just couldn\'t hit the target. "The United fans whistling for the final whistle was like music to my ears but we just couldn\'t make the breakthrough. "If we can add two or three players in the transfer window to help the players then that will be fantastic. The players know it\'s not a threat to them." Man Utd: Kuszczak, O\'Shea, Ferdinand, Vidic, Evra (Brown 84), Ronaldo, Anderson, Carrick, Nani, Park (Hargreaves 75), Tevez (Saha 71).Subs Not Used: Heaton, Pique. Booked: Brown. Goals: Tevez 25. Birmingham: Maik Taylor, Kelly, Jaidi, Ridgewell, Queudrue, McSheffrey (De Ridder 67), Nafti (Palacios 81), Muamba, Larsson, Jerome (Forssell 67), O\'Connor.Subs Not Used: Doyle, Parnaby. Booked: Ridgewell, Queudrue, Nafti, Palacios. Att: 75,459 Ref: Peter Walton (Northamptonshire). BBC Sport Player Rater man of the match: Manchester United\'s Carlos Tevez 8.15 Please note that you can still give the players marks out of 10 on BBC Sport\'s Player Rater after the match has finished.Player Rater Ronaldo partnered Tevez in the centre of attack with Wayne Rooney still absent with a virus and Ryan Giggs not even on the bench. Birmingham boss Alex McLeish - once a protege of Ferguson in their days together at Aberdeen - started with two up front. 606: DEBATE Hav

In [8]:
# Determine the source of an article from the url found by the Google search

from urllib.parse import urlparse

# A set of all trusted sources: aim is that found urls will include one of these within domain name
# NEEDS UPDATING TO INCLUDE MORE SOURCES
trusted_sources = {
    "bbc",
    "skysports",
    "espn",
    "rte"
}

def get_source(url):
    domain = urlparse(url).netloc.lower()               # netloc extracts the network location: i.e. "https://www.example.com:8080/page" goes to "www.example.com:8080"
    for name in trusted_sources:
        if name in domain:                              # Check if one of the trusted sources is in the domain name
            return name
    return "other"

# Testing the function
get_source("http://news.bbc.co.uk/sport2/hi/football/eng_prem/7163892.stm")

'bbc'

In [9]:
# Build article records into a Dataframe

# Create a list with an entry for each article from a trusted source for each match
article_records = []
for _, row in df.iterrows():                        # iterrows() iterates through tuples (*,*) of row index and corresponding one row Dataframe
    match_id = row["match_id"]
    urls = row["article urls"]
    for url in urls:
        source = get_source(url)
        text = extract_article(url)[:32700]         # Limit the number of characters in the text: Excel can only store up to approx 32700 characters before going to a new cell
        
        # Add source, url and text for each trusted article for a given match
        if source in trusted_sources and text:      
            article_records.append({
                "match_id":match_id,
                "source":source,
                "url": url,
                "text": text
            })

# Convert data to a dataframe and store into a csv file
article_df = pd.DataFrame(article_records)
article_df.to_csv("articles.csv", index=False)