In [10]:
import pandas as pd

# Read in dataset
df = pd.read_csv("clean_matches.csv")
df

,date,ground,home team,home score,away team,away score,goalscorer(s)
0,2006-07-26,Murrayfield,Hearts,3,Siroki Brijeg,0,"['Branimir Arnic (og)', 'Ibrahim Tall', 'Roman..."
1,2008-01-01,Old Trafford,Man United,1,Birmingham,0,['Carlos Tevez']
2,2008-11-01,Old Trafford,Man United,4,Hull,3,"['Cristiano Ronaldo (x2)', 'Nemanja Vidic', 'M..."
3,2008-11-19,Windsor Park,NI,0,Hungary,2,"['Sandor Torghelle', 'Zoltan Gera']"
4,2010-10-30,Camp Nou,Barcelona,5,Sevilla,0,"['Lionel Messi (x2)', 'David Villa (x2)', 'Dan..."
5,2012-02-29,Windsor Park,NI,0,Norway,3,"['Harvard Nordtveit', 'Tarik Elyounoussi', 'Es..."
6,2012-08-04,Portman Road,Ipswich,3,West Ham,1,"['Michael Chopra', 'Luke Chambers', 'Jason Sco..."
7,2012-08-08,Old Trafford,Brazil,3,South Korea,0,"['Romulo', 'Leandro Damiao (x2)']"
8,2016-01-19,Villa Park,Aston Villa,2,Wycombe,0,"['Cieran Clark', 'Idrissa Gana Gueye']"
9,2016-03-28,Windsor Park,NI,1,Slovenia,0,['Conor Washington']
10,2017-05-11,Old Trafford,Man United,1,Celta Vigo,1,"['Marounne Fellaini', 'Facundo Roncaglia']"
11,2017-09-30,One Call Stadium,Mansfield,3,Notts County,1,"['Danny Rose (x2)', 'Richard Duffy (og)', 'Car..."
12,2017-10-28,Wanda Metropolitano,Atletico Madrid,1,Villareal,1,"['Angel Correa', 'Carlos Bacca']"
13,2017-11-25,Meadow Lane,Notts County,2,Colchester,1,"['Shola Ameobi', 'Ryan Yates', 'Sanmu Odelusi']"
14,2017-12-14,Old Trafford,Man United,1,Bournemouth,0,['Romelu Lukaku']
15,2018-07-28,Panasonic Stadium,Gamba Osaka,1,Kashima Antlers,1,"['Koki Yonekura', 'Koki Machido']"
16,2018-08-11,City Ground,Nottingham Forest,1,Reading,0,['Hilal Soudani']
17,2019-10-10,Old Trafford,Man United,3,Brighton,1,"['Andreas Pereira', 'Scott McTominay', 'Lewis ..."
18,2019-12-01,Old Trafford,Man United,2,Aston Villa,2,"['Jack Grealish', 'Tom Heaton (og)', 'Victor L..."
19,2019-12-14,King Power Stadium,Leicester,1,Norwich,1,"['Teemu Pukki', 'Tim Krul (og)']"
20,2020-02-24,Old Trafford,Man United,3,Watford,0,"['Bruno Fernandes', 'Antony Martial', 'Mason G..."
21,2021-12-11,Carrow Road,Norwich,0,Man United,1,['Cristiano Ronaldo']
22,2022-02-05,Molineax,Wolves,0,Norwich,1,['Kenny McLean']
23,2022-04-30,Villa Park,Aston Villa,2,Norwich,0,"['Ollie Watkins', 'Danny Ings']"
24,2022-05-15,Molineax,Wolves,1,Norwich,1,"['Teemu Pukki', 'Rayan Ait-Nouri']"
25,2022-11-11,Old Trafford,Man United,4,Aston Villa,2,"['Ollie Watkins', 'Antony Martial', 'Diogo Dal..."
26,2023-04-29,Hawthorns,West Brown,2,Norwich,1,"['Josh Sargent', 'Connor Townsend', 'Jed Walla..."
27,2023-09-03,Emirates Stadium,Arsenal,3,Man United,1,"['Marcus Rashford', 'Martin Odegaard', 'Declan..."
28,2024-02-11,Olympic Stadium,West Ham,0,Arsenal,6,"['William Saliba', 'Bakayo Saka (x2)', 'Gabrie..."
29,2024-04-01,Cledara Abbey Stadium,Cambridge,3,Wigan,1,"['Gassan Ahadme (x2)', 'Danny Andrew', 'Martia..."
30,2024-04-04,Stamford Bridge,Chelsea,4,Man United,3,"['Connor Gallagher', 'Cole Palmer (x3)', 'Alej..."
31,2024-04-23,Cledara Abbey Stadium,Cambridge,1,Wycombe,1,"['Gassan Ahadme', 'Luke Leahy']"
32,2024-08-17,Cledara Abbey Stadium,Cambridge,0,Crawley,1,['Ade Adeyamo']
33,2024-09-24,Stamford Bridge,Chelsea,5,Barrow,0,"['Christopher Nkunku (x3)', 'Pedro Neto', 'Pau..."
34,2024-10-26,Cledara Abbey Stadium,Cambridge,1,Burton,0,['Jordan Cousins']
35,2024-11-26,Cledara Abbey Stadium,Cambridge,1,Bolton,1,"['Aaron Collins', 'Sulley Kaikai']"
36,2025-01-25,Cledara Abbey Stadium,Cambridge,3,Mansfield,2,"['Michael Morrison', 'Josh Stokes', 'Ryan Loft..."
37,2025-03-04,Cledara Abbey Stadium,Cambridge,0,Stevenage,1,['Jamie Reid']
38,2025-03-15,Cledara Abbey Stadium,Cambridge,0,Peterborough,1,['Tayo Edun']
39,2025-04-21,Cledara Abbey Stadium,Cambridge,1,Leyton Orient,2,"['Josh Stokes', 'Charlie Kelman', 'Jamie Donley']"
40,2025-08-02,Cledara Abbey Stadium,Cambridge,1,Cheltenham,0,['Louis Appere']
41,2025-08-30,Cledara Abbey Stadium,Cambridge,2,Newport,0,"['Kell Watts', 'James Brophy']"
42,2025-10-25,Old Trafford,Man United,4,Brighton,2,"['Matheus Cunha', 'Casemiro', 'Bryan Mbeumo (x..."
43,2025-12-15,Old Trafford,Man United,4,Bournemouth,4,"['Amad Diallo', 'Antoine Semenyo', 'Casemiro',..."
44,2026-03-21,Cledara Abbey Stadium,Cambridge,1,Salford,0,['James Gibbons']
45,2026-04-02,Cledara Abbey Stadium,Cambridge,1,Swindon,1,"['Ben Knight', 'Joel McGregor']"

In [11]:
import calendar

def build_search_query(match):
    home_team = match["home team"]
    away_team = match["away team"]
    month = calendar.month_name[int(match["date"][5:7])]
    year = match["date"][0:4]
    return f"{home_team} vs {away_team} in {month} {year}"

In [4]:
build_search_query(df.iloc[44])

'Cambridge vs Salford in March 2026'

In [12]:
df["search query"] = df.apply(build_search_query, axis=1)
df

,date,ground,home team,home score,away team,away score,goalscorer(s),search query
0,2006-07-26,Murrayfield,Hearts,3,Siroki Brijeg,0,"['Branimir Arnic (og)', 'Ibrahim Tall', 'Roman...",Hearts vs Siroki Brijeg in July 2006
1,2008-01-01,Old Trafford,Man United,1,Birmingham,0,['Carlos Tevez'],Man United vs Birmingham in January 2008
2,2008-11-01,Old Trafford,Man United,4,Hull,3,"['Cristiano Ronaldo (x2)', 'Nemanja Vidic', 'M...",Man United vs Hull in November 2008
3,2008-11-19,Windsor Park,NI,0,Hungary,2,"['Sandor Torghelle', 'Zoltan Gera']",NI vs Hungary in November 2008
4,2010-10-30,Camp Nou,Barcelona,5,Sevilla,0,"['Lionel Messi (x2)', 'David Villa (x2)', 'Dan...",Barcelona vs Sevilla in October 2010
5,2012-02-29,Windsor Park,NI,0,Norway,3,"['Harvard Nordtveit', 'Tarik Elyounoussi', 'Es...",NI vs Norway in February 2012
6,2012-08-04,Portman Road,Ipswich,3,West Ham,1,"['Michael Chopra', 'Luke Chambers', 'Jason Sco...",Ipswich vs West Ham in August 2012
7,2012-08-08,Old Trafford,Brazil,3,South Korea,0,"['Romulo', 'Leandro Damiao (x2)']",Brazil vs South Korea in August 2012
8,2016-01-19,Villa Park,Aston Villa,2,Wycombe,0,"['Cieran Clark', 'Idrissa Gana Gueye']",Aston Villa vs Wycombe in January 2016
9,2016-03-28,Windsor Park,NI,1,Slovenia,0,['Conor Washington'],NI vs Slovenia in March 2016
10,2017-05-11,Old Trafford,Man United,1,Celta Vigo,1,"['Marounne Fellaini', 'Facundo Roncaglia']",Man United vs Celta Vigo in May 2017
11,2017-09-30,One Call Stadium,Mansfield,3,Notts County,1,"['Danny Rose (x2)', 'Richard Duffy (og)', 'Car...",Mansfield vs Notts County in September 2017
12,2017-10-28,Wanda Metropolitano,Atletico Madrid,1,Villareal,1,"['Angel Correa', 'Carlos Bacca']",Atletico Madrid vs Villareal in October 2017
13,2017-11-25,Meadow Lane,Notts County,2,Colchester,1,"['Shola Ameobi', 'Ryan Yates', 'Sanmu Odelusi']",Notts County vs Colchester in November 2017
14,2017-12-14,Old Trafford,Man United,1,Bournemouth,0,['Romelu Lukaku'],Man United vs Bournemouth in December 2017
15,2018-07-28,Panasonic Stadium,Gamba Osaka,1,Kashima Antlers,1,"['Koki Yonekura', 'Koki Machido']",Gamba Osaka vs Kashima Antlers in July 2018
16,2018-08-11,City Ground,Nottingham Forest,1,Reading,0,['Hilal Soudani'],Nottingham Forest vs Reading in August 2018
17,2019-10-10,Old Trafford,Man United,3,Brighton,1,"['Andreas Pereira', 'Scott McTominay', 'Lewis ...",Man United vs Brighton in October 2019
18,2019-12-01,Old Trafford,Man United,2,Aston Villa,2,"['Jack Grealish', 'Tom Heaton (og)', 'Victor L...",Man United vs Aston Villa in December 2019
19,2019-12-14,King Power Stadium,Leicester,1,Norwich,1,"['Teemu Pukki', 'Tim Krul (og)']",Leicester vs Norwich in December 2019
20,2020-02-24,Old Trafford,Man United,3,Watford,0,"['Bruno Fernandes', 'Antony Martial', 'Mason G...",Man United vs Watford in February 2020
21,2021-12-11,Carrow Road,Norwich,0,Man United,1,['Cristiano Ronaldo'],Norwich vs Man United in December 2021
22,2022-02-05,Molineax,Wolves,0,Norwich,1,['Kenny McLean'],Wolves vs Norwich in February 2022
23,2022-04-30,Villa Park,Aston Villa,2,Norwich,0,"['Ollie Watkins', 'Danny Ings']",Aston Villa vs Norwich in April 2022
24,2022-05-15,Molineax,Wolves,1,Norwich,1,"['Teemu Pukki', 'Rayan Ait-Nouri']",Wolves vs Norwich in May 2022
25,2022-11-11,Old Trafford,Man United,4,Aston Villa,2,"['Ollie Watkins', 'Antony Martial', 'Diogo Dal...",Man United vs Aston Villa in November 2022
26,2023-04-29,Hawthorns,West Brown,2,Norwich,1,"['Josh Sargent', 'Connor Townsend', 'Jed Walla...",West Brown vs Norwich in April 2023
27,2023-09-03,Emirates Stadium,Arsenal,3,Man United,1,"['Marcus Rashford', 'Martin Odegaard', 'Declan...",Arsenal vs Man United in September 2023
28,2024-02-11,Olympic Stadium,West Ham,0,Arsenal,6,"['William Saliba', 'Bakayo Saka (x2)', 'Gabrie...",West Ham vs Arsenal in February 2024
29,2024-04-01,Cledara Abbey Stadium,Cambridge,3,Wigan,1,"['Gassan Ahadme (x2)', 'Danny Andrew', 'Martia...",Cambridge vs Wigan in April 2024
30,2024-04-04,Stamford Bridge,Chelsea,4,Man United,3,"['Connor Gallagher', 'Cole Palmer (x3)', 'Alej...",Chelsea vs Man United in April 2024
31,2024-04-23,Cledara Abbey Stadium,Cambridge,1,Wycombe,1,"['Gassan Ahadme', 'Luke Leahy']",Cambridge vs Wycombe in April 2024
32,2024-08-17,Cledara Abbey Stadium,Cambridge,0,Crawley,1,['Ade Adeyamo'],Cambridge vs Crawley in August 2024
33,2024-09-24,Stamford Bridge,Chelsea,5,Barrow,0,"['Christopher Nkunku (x3)', 'Pedro Neto', 'Pau...",Chelsea vs Barrow in September 2024
34,2024-10-26,Cledara Abbey Stadium,Cambridge,1,Burton,0,['Jordan Cousins'],Cambridge vs Burton in October 2024
35,2024-11-26,Cledara Abbey Stadium,Cambridge,1,Bolton,1,"['Aaron Collins', 'Sulley Kaikai']",Cambridge vs Bolton in November 2024
36,2025-01-25,Cledara Abbey Stadium,Cambridge,3,Mansfield,2,"['Michael Morrison', 'Josh Stokes', 'Ryan Loft...",Cambridge vs Mansfield in January 2025
37,2025-03-04,Cledara Abbey Stadium,Cambridge,0,Stevenage,1,['Jamie Reid'],Cambridge vs Stevenage in March 2025
38,2025-03-15,Cledara Abbey Stadium,Cambridge,0,Peterborough,1,['Tayo Edun'],Cambridge vs Peterborough in March 2025
39,2025-04-21,Cledara Abbey Stadium,Cambridge,1,Leyton Orient,2,"['Josh Stokes', 'Charlie Kelman', 'Jamie Donley']",Cambridge vs Leyton Orient in April 2025
40,2025-08-02,Cledara Abbey Stadium,Cambridge,1,Cheltenham,0,['Louis Appere'],Cambridge vs Cheltenham in August 2025
41,2025-08-30,Cledara Abbey Stadium,Cambridge,2,Newport,0,"['Kell Watts', 'James Brophy']",Cambridge vs Newport in August 2025
42,2025-10-25,Old Trafford,Man United,4,Brighton,2,"['Matheus Cunha', 'Casemiro', 'Bryan Mbeumo (x...",Man United vs Brighton in October 2025
43,2025-12-15,Old Trafford,Man United,4,Bournemouth,4,"['Amad Diallo', 'Antoine Semenyo', 'Casemiro',...",Man United vs Bournemouth in December 2025
44,2026-03-21,Cledara Abbey Stadium,Cambridge,1,Salford,0,['James Gibbons'],Cambridge vs Salford in March 2026
45,2026-04-02,Cledara Abbey Stadium,Cambridge,1,Swindon,1,"['Ben Knight', 'Joel McGregor']",Cambridge vs Swindon in April 2026

In [ ]:
from dotenv import load_dotenv
import os

load_dotenv()
api_key = os.getenv("SERPAPI_KEY")

In [6]:
from serpapi import GoogleSearch

def get_urls(query):
    params = {
        "q": query,
        "api_key": api_key,
        "num": 20
    }

    search = GoogleSearch(params)
    results = search.get_dict()

    return [r["link"] for r in results.get("organic_results", [])]

urls = get_urls("Man United vs Birmingham in January 2008")
urls

['https://www.youtube.com/watch?v=givC4ZvbqYc',
 'https://www.skysports.com/football/manchester-united-vs-birmingham-city/teams/94538',
 'https://www.transfermarkt.us/manchester-united_birmingham-city/index/spielbericht/81687',
 'https://www.manutd.com/en/videos/detail/man-utd-1-birmingham-city-0-extended-highlights-premier-league-2007-08',
 'https://www.statmuse.com/fc/ask/full-time-scores-of-man-u-vs-birmingham-in-premiere-league-match-in-2008',
 'http://news.bbc.co.uk/sport2/hi/football/eng_prem/7163892.stm',
 'https://www.premierleague.com/en/match/128642/manchester-united-vs-birmingham-city',
 'https://www.espn.ph/football/report/_/gameId/220076',
 'https://www.footballcritic.com/premier-league-manchester-united-fc-birmingham-city-fc/match-stats/42194']

In [14]:
# View the urls from the previous cell without needing to send another query to SERPAPI
urls

['https://www.youtube.com/watch?v=givC4ZvbqYc',
 'https://www.skysports.com/football/manchester-united-vs-birmingham-city/teams/94538',
 'https://www.transfermarkt.us/manchester-united_birmingham-city/index/spielbericht/81687',
 'https://www.manutd.com/en/videos/detail/man-utd-1-birmingham-city-0-extended-highlights-premier-league-2007-08',
 'https://www.statmuse.com/fc/ask/full-time-scores-of-man-u-vs-birmingham-in-premiere-league-match-in-2008',
 'http://news.bbc.co.uk/sport2/hi/football/eng_prem/7163892.stm',
 'https://www.premierleague.com/en/match/128642/manchester-united-vs-birmingham-city',
 'https://www.espn.ph/football/report/_/gameId/220076',
 'https://www.footballcritic.com/premier-league-manchester-united-fc-birmingham-city-fc/match-stats/42194']

In [ ]:
# Able to redefine urls from above cell if I start a new session without needing to re-use a SERPAPI search
urls = ['https://www.youtube.com/watch?v=givC4ZvbqYc',
 'https://www.skysports.com/football/manchester-united-vs-birmingham-city/teams/94538',
 'https://www.transfermarkt.us/manchester-united_birmingham-city/index/spielbericht/81687',
 'https://www.manutd.com/en/videos/detail/man-utd-1-birmingham-city-0-extended-highlights-premier-league-2007-08',
 'https://www.statmuse.com/fc/ask/full-time-scores-of-man-u-vs-birmingham-in-premiere-league-match-in-2008',
 'http://news.bbc.co.uk/sport2/hi/football/eng_prem/7163892.stm',
 'https://www.premierleague.com/en/match/128642/manchester-united-vs-birmingham-city',
 'https://www.espn.ph/football/report/_/gameId/220076',
 'https://www.footballcritic.com/premier-league-manchester-united-fc-birmingham-city-fc/match-stats/42194']

In [17]:
# Test on one match before expanding to all to preserve SerpAPI queries

sample_df = df.iloc[[1]].copy()
sample_df["article urls"] = [urls]
sample_df

,date,ground,home team,home score,away team,away score,goalscorer(s),search query,article urls
1,2008-01-01,Old Trafford,Man United,1,Birmingham,0,['Carlos Tevez'],Man United vs Birmingham in January 2008,"[https://www.youtube.com/watch?v=givC4ZvbqYc, ..."