In [1]:
import pandas as pd

# Read in dataset from data preprocessing
df = pd.read_csv("../data/clean_matches.csv")
df

,match_id,date,ground,home team,home score,away team,away score,goalscorer(s)
0,1,2008-01-01,Old Trafford,Man United,1,Birmingham,0,['Carlos Tevez']
1,2,2008-11-01,Old Trafford,Man United,4,Hull,3,"['Cristiano Ronaldo (x2)', 'Nemanja Vidic', 'M..."
2,3,2016-01-19,Villa Park,Aston Villa,2,Wycombe,0,"['Cieran Clark', 'Idrissa Gana Gueye']"
3,4,2017-05-11,Old Trafford,Man United,1,Celta Vigo,1,"['Marounne Fellaini', 'Facundo Roncaglia']"
4,5,2017-12-14,Old Trafford,Man United,1,Bournemouth,0,['Romelu Lukaku']
5,6,2019-10-10,Old Trafford,Man United,3,Brighton,1,"['Andreas Pereira', 'Scott McTominay', 'Lewis ..."
6,7,2019-12-01,Old Trafford,Man United,2,Aston Villa,2,"['Jack Grealish', 'Tom Heaton (og)', 'Victor L..."
7,8,2019-12-14,King Power Stadium,Leicester,1,Norwich,1,"['Teemu Pukki', 'Tim Krul (og)']"
8,9,2020-02-24,Old Trafford,Man United,3,Watford,0,"['Bruno Fernandes', 'Antony Martial', 'Mason G..."
9,10,2021-12-11,Carrow Road,Norwich,0,Man United,1,['Cristiano Ronaldo']
10,11,2022-02-05,Molineax,Wolves,0,Norwich,1,['Kenny McLean']
11,12,2022-04-30,Villa Park,Aston Villa,2,Norwich,0,"['Ollie Watkins', 'Danny Ings']"
12,13,2022-05-15,Molineax,Wolves,1,Norwich,1,"['Teemu Pukki', 'Rayan Ait-Nouri']"
13,14,2022-11-11,Old Trafford,Man United,4,Aston Villa,2,"['Ollie Watkins', 'Antony Martial', 'Diogo Dal..."
14,15,2023-04-29,Hawthorns,West Brown,2,Norwich,1,"['Josh Sargent', 'Connor Townsend', 'Jed Walla..."
15,16,2023-09-03,Emirates Stadium,Arsenal,3,Man United,1,"['Marcus Rashford', 'Martin Odegaard', 'Declan..."
16,17,2024-02-11,Olympic Stadium,West Ham,0,Arsenal,6,"['William Saliba', 'Bakayo Saka (x2)', 'Gabrie..."
17,18,2024-04-04,Stamford Bridge,Chelsea,4,Man United,3,"['Connor Gallagher', 'Cole Palmer (x3)', 'Alej..."
18,19,2024-09-24,Stamford Bridge,Chelsea,5,Barrow,0,"['Christopher Nkunku (x3)', 'Pedro Neto', 'Pau..."
19,20,2025-10-25,Old Trafford,Man United,4,Brighton,2,"['Matheus Cunha', 'Casemiro', 'Bryan Mbeumo (x..."
20,21,2025-12-15,Old Trafford,Man United,4,Bournemouth,4,"['Amad Diallo', 'Antoine Semenyo', 'Casemiro',..."

In [2]:
# Function that builds the search query that will be input to Google
import calendar

def build_search_query(match):                              # Match will be row from the dataset
    # Set up variables that will be used in the string for search query
    home_team = match["home team"]
    away_team = match["away team"]
    home_score = match["home score"]
    away_score = match["away score"]

    month = calendar.month_name[int(match["date"][5:7])]    # Calendar converts the numbers 1-12 to the corresponding months January-December
    year = match["date"][0:4]
    return f"{home_team} {home_score} {away_team} {away_score} {month} {year} match report"  # Return the search query in an f-string

In [3]:
# Add the seach query as a column in the database
df["search query"] = df.apply(build_search_query, axis=1)
df

,match_id,date,ground,home team,home score,away team,away score,goalscorer(s),search query
0,1,2008-01-01,Old Trafford,Man United,1,Birmingham,0,['Carlos Tevez'],Man United 1 Birmingham 0 January 2008 match r...
1,2,2008-11-01,Old Trafford,Man United,4,Hull,3,"['Cristiano Ronaldo (x2)', 'Nemanja Vidic', 'M...",Man United 4 Hull 3 November 2008 match report
2,3,2016-01-19,Villa Park,Aston Villa,2,Wycombe,0,"['Cieran Clark', 'Idrissa Gana Gueye']",Aston Villa 2 Wycombe 0 January 2016 match report
3,4,2017-05-11,Old Trafford,Man United,1,Celta Vigo,1,"['Marounne Fellaini', 'Facundo Roncaglia']",Man United 1 Celta Vigo 1 May 2017 match report
4,5,2017-12-14,Old Trafford,Man United,1,Bournemouth,0,['Romelu Lukaku'],Man United 1 Bournemouth 0 December 2017 match...
5,6,2019-10-10,Old Trafford,Man United,3,Brighton,1,"['Andreas Pereira', 'Scott McTominay', 'Lewis ...",Man United 3 Brighton 1 October 2019 match report
6,7,2019-12-01,Old Trafford,Man United,2,Aston Villa,2,"['Jack Grealish', 'Tom Heaton (og)', 'Victor L...",Man United 2 Aston Villa 2 December 2019 match...
7,8,2019-12-14,King Power Stadium,Leicester,1,Norwich,1,"['Teemu Pukki', 'Tim Krul (og)']",Leicester 1 Norwich 1 December 2019 match report
8,9,2020-02-24,Old Trafford,Man United,3,Watford,0,"['Bruno Fernandes', 'Antony Martial', 'Mason G...",Man United 3 Watford 0 February 2020 match report
9,10,2021-12-11,Carrow Road,Norwich,0,Man United,1,['Cristiano Ronaldo'],Norwich 0 Man United 1 December 2021 match report
10,11,2022-02-05,Molineax,Wolves,0,Norwich,1,['Kenny McLean'],Wolves 0 Norwich 1 February 2022 match report
11,12,2022-04-30,Villa Park,Aston Villa,2,Norwich,0,"['Ollie Watkins', 'Danny Ings']",Aston Villa 2 Norwich 0 April 2022 match report
12,13,2022-05-15,Molineax,Wolves,1,Norwich,1,"['Teemu Pukki', 'Rayan Ait-Nouri']",Wolves 1 Norwich 1 May 2022 match report
13,14,2022-11-11,Old Trafford,Man United,4,Aston Villa,2,"['Ollie Watkins', 'Antony Martial', 'Diogo Dal...",Man United 4 Aston Villa 2 November 2022 match...
14,15,2023-04-29,Hawthorns,West Brown,2,Norwich,1,"['Josh Sargent', 'Connor Townsend', 'Jed Walla...",West Brown 2 Norwich 1 April 2023 match report
15,16,2023-09-03,Emirates Stadium,Arsenal,3,Man United,1,"['Marcus Rashford', 'Martin Odegaard', 'Declan...",Arsenal 3 Man United 1 September 2023 match re...
16,17,2024-02-11,Olympic Stadium,West Ham,0,Arsenal,6,"['William Saliba', 'Bakayo Saka (x2)', 'Gabrie...",West Ham 0 Arsenal 6 February 2024 match report
17,18,2024-04-04,Stamford Bridge,Chelsea,4,Man United,3,"['Connor Gallagher', 'Cole Palmer (x3)', 'Alej...",Chelsea 4 Man United 3 April 2024 match report
18,19,2024-09-24,Stamford Bridge,Chelsea,5,Barrow,0,"['Christopher Nkunku (x3)', 'Pedro Neto', 'Pau...",Chelsea 5 Barrow 0 September 2024 match report
19,20,2025-10-25,Old Trafford,Man United,4,Brighton,2,"['Matheus Cunha', 'Casemiro', 'Bryan Mbeumo (x...",Man United 4 Brighton 2 October 2025 match report
20,21,2025-12-15,Old Trafford,Man United,4,Bournemouth,4,"['Amad Diallo', 'Antoine Semenyo', 'Casemiro',...",Man United 4 Bournemouth 4 December 2025 match...

In [4]:
# API key needs to be kept private from public GITHUB repository
# Key stored in an .env file
# .env file listed within .gitignore
# This cell reads in the key and stores it with api_key

from dotenv import load_dotenv
import os

load_dotenv()
api_key = os.getenv("SERPAPI_KEY")

In [5]:
# Function that performs the Google search query
# Uses SerpAPI

from serpapi import GoogleSearch

def get_urls(match):
    # Parameters for the Google search
    params = {
        "q": match["search query"],                     # The string to be query                
        "api_key": api_key,             # The SerpAPI key
        "num": 20,                       # Max 20 links, but will naturally restrict to the first page of Google searches
        "google_domain": "google.co.uk",
        "location": "London, England, United Kingdom",
        "gl": "uk",
        "hl": "en"
    }

    search = GoogleSearch(params)       
    results = search.get_dict()         # Sends request to the API

    return [r["link"] for r in results.get("organic_results", [])]          # Extract links

In [7]:
# Test the function get_urls on the query generated for one of the matches
# Need to be careful about overusing this function: get 250 queries per month through free tier of SerpAPI

urls = get_urls(df.iloc[[1]])
urls

['https://www.espn.com/soccer/match/_/gameId/220076/birmingham-city-manchester-united',
 'https://www.premierleague.com/en/match/128642/manchester-united-vs-birmingham-city',
 'http://news.bbc.co.uk/sport2/hi/football/eng_prem/7163892.stm',
 'https://www.skysports.com/football/manchester-united-vs-birmingham-city/teams/94538',
 'https://www.manutd.com/en/mutv/videos/detail/man-utd-1-birmingham-city-0-extended-highlights-premier-league-2007-08',
 'https://www.mufcinfo.com/manupag/match_data/match_sql.php?my_match_date=2008-01-01',
 'https://www.manutd.com/en/mutv/videos/detail/man-utd-1-birmingham-city-0-extended-highlights-premier-league-2009-10',
 'https://en.wikipedia.org/wiki/2006%E2%80%9307_Manchester_United_F.C._season']

In [ ]:
# Access the urls variable from the previous cell without needing to send another query to SERPAPI
urls

In [ ]:
# Able to redefine urls from above cell if I start a new session without needing to re-use a SERPAPI search
urls = ['https://www.youtube.com/watch?v=givC4ZvbqYc',
 'https://www.skysports.com/football/manchester-united-vs-birmingham-city/teams/94538',
 'https://www.transfermarkt.us/manchester-united_birmingham-city/index/spielbericht/81687',
 'https://www.manutd.com/en/videos/detail/man-utd-1-birmingham-city-0-extended-highlights-premier-league-2007-08',
 'https://www.statmuse.com/fc/ask/full-time-scores-of-man-u-vs-birmingham-in-premiere-league-match-in-2008',
 'http://news.bbc.co.uk/sport2/hi/football/eng_prem/7163892.stm',
 'https://www.premierleague.com/en/match/128642/manchester-united-vs-birmingham-city',
 'https://www.espn.ph/football/report/_/gameId/220076',
 'https://www.footballcritic.com/premier-league-manchester-united-fc-birmingham-city-fc/match-stats/42194']

In [ ]:
# Test on one match before expanding to all to preserve SerpAPI queries
# Remove this cell before roll-out

df = df.iloc[[1]].copy()        # Make a copy of the second entry in a sample dataframe
df["article urls"] = [urls]     # Add a new column of the list of url strings
df

In [36]:
df = df.iloc[[42,43]].copy()
df

,match_id,date,ground,home team,home score,away team,away score,goalscorer(s),search query
42,43,2025-10-25,Old Trafford,Man United,4,Brighton,2,"['Matheus Cunha', 'Casemiro', 'Bryan Mbeumo (x...",Man United 4 Brighton 2 October 2025 match report
43,44,2025-12-15,Old Trafford,Man United,4,Bournemouth,4,"['Amad Diallo', 'Antoine Semenyo', 'Casemiro',...",Man United 4 Bournemouth 4 December 2025 match...

In [6]:
#df["search query"] = df.apply(build_search_query, axis=1)

df["article urls"] = df.apply(get_urls, axis=1)

In [7]:
df

,match_id,date,ground,home team,home score,away team,away score,goalscorer(s),search query,article urls
0,1,2008-01-01,Old Trafford,Man United,1,Birmingham,0,['Carlos Tevez'],Man United 1 Birmingham 0 January 2008 match r...,[https://www.espn.co.uk/football/match/_/gameI...
1,2,2008-11-01,Old Trafford,Man United,4,Hull,3,"['Cristiano Ronaldo (x2)', 'Nemanja Vidic', 'M...",Man United 4 Hull 3 November 2008 match report,[https://www.espn.co.uk/football/match/_/gameI...
2,3,2016-01-19,Villa Park,Aston Villa,2,Wycombe,0,"['Cieran Clark', 'Idrissa Gana Gueye']",Aston Villa 2 Wycombe 0 January 2016 match report,[https://www.espn.co.uk/football/match/_/gameI...
3,4,2017-05-11,Old Trafford,Man United,1,Celta Vigo,1,"['Marounne Fellaini', 'Facundo Roncaglia']",Man United 1 Celta Vigo 1 May 2017 match report,[https://www.espn.co.uk/football/match/_/gameI...
4,5,2017-12-14,Old Trafford,Man United,1,Bournemouth,0,['Romelu Lukaku'],Man United 1 Bournemouth 0 December 2017 match...,[https://www.espn.co.uk/football/match/_/gameI...
5,6,2019-10-10,Old Trafford,Man United,3,Brighton,1,"['Andreas Pereira', 'Scott McTominay', 'Lewis ...",Man United 3 Brighton 1 October 2019 match report,[https://www.premierleague.com/en/match/987602...
6,7,2019-12-01,Old Trafford,Man United,2,Aston Villa,2,"['Jack Grealish', 'Tom Heaton (og)', 'Victor L...",Man United 2 Aston Villa 2 December 2019 match...,[https://www.manutd.com/en/news/match-report-u...
7,8,2019-12-14,King Power Stadium,Leicester,1,Norwich,1,"['Teemu Pukki', 'Tim Krul (og)']",Leicester 1 Norwich 1 December 2019 match report,[https://www.espn.co.uk/football/report/_/game...
8,9,2020-02-24,Old Trafford,Man United,3,Watford,0,"['Bruno Fernandes', 'Antony Martial', 'Mason G...",Man United 3 Watford 0 February 2020 match report,[https://www.espn.co.uk/football/match/_/gameI...
9,10,2021-12-11,Carrow Road,Norwich,0,Man United,1,['Cristiano Ronaldo'],Norwich 0 Man United 1 December 2021 match report,[https://www.espn.co.uk/football/match/_/gameI...
10,11,2022-02-05,Molineax,Wolves,0,Norwich,1,['Kenny McLean'],Wolves 0 Norwich 1 February 2022 match report,[https://www.wolves.co.uk/news/mens-first-team...
11,12,2022-04-30,Villa Park,Aston Villa,2,Norwich,0,"['Ollie Watkins', 'Danny Ings']",Aston Villa 2 Norwich 0 April 2022 match report,[https://www.espn.co.uk/football/match/_/gameI...
12,13,2022-05-15,Molineax,Wolves,1,Norwich,1,"['Teemu Pukki', 'Rayan Ait-Nouri']",Wolves 1 Norwich 1 May 2022 match report,[https://www.wolves.co.uk/news/mens-first-team...
13,14,2022-11-11,Old Trafford,Man United,4,Aston Villa,2,"['Ollie Watkins', 'Antony Martial', 'Diogo Dal...",Man United 4 Aston Villa 2 November 2022 match...,[https://www.espn.co.uk/football/match/_/gameI...
14,15,2023-04-29,Hawthorns,West Brown,2,Norwich,1,"['Josh Sargent', 'Connor Townsend', 'Jed Walla...",West Brown 2 Norwich 1 April 2023 match report,[https://www.espn.co.uk/football/match/_/gameI...
15,16,2023-09-03,Emirates Stadium,Arsenal,3,Man United,1,"['Marcus Rashford', 'Martin Odegaard', 'Declan...",Arsenal 3 Man United 1 September 2023 match re...,"[https://www.arsenal.com/, https://www.instagr..."
16,17,2024-02-11,Olympic Stadium,West Ham,0,Arsenal,6,"['William Saliba', 'Bakayo Saka (x2)', 'Gabrie...",West Ham 0 Arsenal 6 February 2024 match report,[https://www.arsenal.com/news/report-west-ham-...
17,18,2024-04-04,Stamford Bridge,Chelsea,4,Man United,3,"['Connor Gallagher', 'Cole Palmer (x3)', 'Alej...",Chelsea 4 Man United 3 April 2024 match report,[https://www.espn.co.uk/football/match/_/gameI...
18,19,2024-09-24,Stamford Bridge,Chelsea,5,Barrow,0,"['Christopher Nkunku (x3)', 'Pedro Neto', 'Pau...",Chelsea 5 Barrow 0 September 2024 match report,[https://www.chelseafc.com/en/match/chelsea-vs...
19,20,2025-10-25,Old Trafford,Man United,4,Brighton,2,"['Matheus Cunha', 'Casemiro', 'Bryan Mbeumo (x...",Man United 4 Brighton 2 October 2025 match report,[https://www.skysports.com/football/news/11661...
20,21,2025-12-15,Old Trafford,Man United,4,Bournemouth,4,"['Amad Diallo', 'Antoine Semenyo', 'Casemiro',...",Man United 4 Bournemouth 4 December 2025 match...,[https://www.premierleague.com/en/match/256205...

In [8]:
for row in df["article urls"]:
    for url in row:
        print(url)
    print("new match")

https://www.espn.co.uk/football/match/_/gameId/220076/birmingham-city-manchester-united
http://news.bbc.co.uk/sport2/hi/football/eng_prem/7163892.stm
https://www.premierleague.com/en/match/128642/manchester-united-vs-birmingham-city
https://www.skysports.com/football/manchester-united-vs-birmingham-city/teams/94538
https://www.manutd.com/en/mutv/videos/detail/man-utd-1-birmingham-city-0-extended-highlights-premier-league-2007-08
https://www.mufcinfo.com/manupag/match_data/match_sql.php?my_match_date=2008-01-01
https://www.espn.co.uk/football/report/_/gameId/220076
https://www.facebook.com/groups/271475672143247/posts/709440608346749/
https://www.facebook.com/football70s80s/videos/birmingham-city-v-manchester-united-1977the-first-saturday-of-the-new-football-s/1747952412818369/
new match
https://www.espn.co.uk/football/match/_/gameId/242601/hull-city-manchester-united
http://news.bbc.co.uk/sport2/hi/football/eng_prem/7684745.stm
https://www.premierleague.com/en/match/266347
https://www.stretford-end.com/2008/11/match-report-manchester-united-4-3-hull-city/
https://mufcinfo.com/manupag/match_data/match_sql.php?my_match_date=2008-11-01
https://en.wikipedia.org/wiki/2008%E2%80%9309_Manchester_United_F.C._season
new match
https://www.espn.co.uk/football/match/_/gameId/441005/wycombe-wanderers-aston-villa
https://www.premierleague.com/en/match/843003
https://www.bbc.co.uk/sport/football/35289310
https://www.youtube.com/watch?v=mdu6Ejs7r1A
https://www.thefa.com/news/2016/jan/09/wycombe-wanderers-v-aston-villa-emirates-fa-cup
https://www.skysports.com/football/aston-villa-vs-wycombe-wanderers/stats/353732
https://www.espn.co.uk/football/match/_/gameId/438636/aston-villa-wycombe-wanderers
https://www.youtube.com/watch?v=q8unYMCjEgQ
https://www.avfc.co.uk/news/2024/september/24/wycombe-wanderers---aston-villa/
https://en.wikipedia.org/wiki/2015%E2%80%9316_Aston_Villa_F.C._season
new match
https://www.espn.co.uk/football/match/_/gameId/478700/celta-vigo-manchester-united
https://www.theguardian.com/football/live/2017/may/04/celta-vigo-v-manchester-united-europa-league-semi-final-first-leg-live
https://www.espn.co.uk/football/match/_/gameId/478702/manchester-united-celta-vigo
https://www.itv.com/news/2017-05-11/europa-league-match-report-manchester-united-1-1-celta-vigo-agg-2-1
https://www.facebook.com/OldTraffordFaithful/posts/manchester-united-fans-at-celta-vigo-away-in-the-europa-league-semi-final-in-201/2768461509870223/
https://www.uefa.com/uefaeuropaleague/match/2019701--man-utd-vs-celta/
https://football.fandom.com/wiki/Manchester_United_v_Celta_Vigo_(Europa_League_2016-17)
https://www.bbc.co.uk/sport/football/39877812
new match
https://www.espn.co.uk/football/match/_/gameId/480740/afc-bournemouth-manchester-united
https://www.premierleague.com/en/match/919056
https://www.facebook.com/mirrorfootball/posts/manchester-united-were-forced-to-settle-for-a-point-at-bournemouth-despite-leadi/1414095757423985/
https://www.theguardian.com/football/live/2017/dec/13/swansea-v-manchester-city-manchester-united-v-bournemouth-and-more-live
https://www.mufcinfo.com/manupag/match_data/match_sql.php?my_match_date=2017-12-13
https://www.youtube.com/watch?v=MlAvBiscrXg
https://www.skysports.com/football/news/11661/11169355/man-utd-1-0-bournemouth-romelu-lukaku-nets-winner-for-hosts
https://www.premierleague.com/en/video/4355496/afc-bournemouth-v-manchester-united-2017-18-full-match-replay
https://analogueboyinadigitalworld.wordpress.com/2017/12/17/manchester-united-1-0-afc-bournemouth-13-12-2017/
new match
https://www.premierleague.com/en/match/987602
https://www.espn.co.uk/football/match/_/gameId/541728/brighton-hove-albion-manchester-united
https://www.facebook.com/8am.media/posts/manchester-united-defeated-brighton-30-on-the-final-day-of-the-english-premier-l/1464194532416925/
https://www.facebook.com/manchesterunited/videos/highlights-united-3-brighton-1-201920/716407315879103/
https://www.manutd.com/en/news/match-report-for-man-utd-v-brighton-in-the-premier-league-25-october-2025
https://www.bbc.co.uk/sport/football/50278822
https://www.premierleague.com/en/video/4356605/manchester-united-v-brighton-and-hove-albion-2019-20-full-match-replay
https://mufcinfo.com/manupag/match_data/match_sql.php?my_match_date=2019-11-10
https://www.facebook.com/kdcglobalcomedian/posts/manchester-united-defeated-brighton-3-0-bruno-goal-and-assist-lammens-clean-shee/1477685561038523/
new match
https://www.manutd.com/en/news/match-report-united-versus-aston-villa-1-december-2019
https://www.espn.co.uk/football/match/_/gameId/541706/aston-villa-manchester-united
https://www.premierleague.com/en/match/1059836
https://www.theguardian.com/football/2019/dec/01/manchester-united-aston-villa-premier-league-match-report
https://www.mufcinfo.com/manupag/match_data/match_sql.php?my_match_date=2019-12-01
https://www.premierleague.com/en/video/4356695/manchester-united-v-aston-villa-2019-20-full-match-replay
https://www.avfc.co.uk/News/2019/12/01/on-the-whistle-villa-man-utd
new match
https://www.espn.co.uk/football/report/_/gameId/541681
https://www.premierleague.com/en/match/1059866
https://www.theguardian.com/football/2019/dec/14/leicester-city-norwich-city-premier-league-match-report
https://www.canaries.co.uk/content/match-report-norwich-city-1-2-leicester-city
https://fosseposse.sbnation.com/2019/12/16/21024042/lessons-leicester-city-norwich-city-chilwell-barnes-gray-pereira-ndidi-soyuncu-pukki
https://www.facebook.com/lcfc/videos/the-highlights-from-our-last-minute-winner-against-norwich-as-we-finish-2-1/1417487577051860/
https://www.espn.co.uk/football/match/_/gameId/541681/norwich-city-leicester-city
https://www.facebook.com/footballfrea/posts/ft-leicester-city-1-1-norwich-norwich-stop-leicesters-eight-match-winning-run-in/440670593275186/
https://www.bbc.co.uk/sport/football/50696492
new match
https://www.espn.co.uk/football/match/_/gameId/541583/watford-manchester-united
https://www.manutd.com/en/news/match-report-from-man-utd-v-watford-23-february-2020
https://www.premierleague.com/en/match/1059968
https://www.theguardian.com/football/2020/feb/23/manchester-united-watford-premier-league-match-report
https://www.facebook.com/DailyMonitor/posts/73-manchester-uniteds-marson-greenwood-scores-to-make-it-3-0-watford/10156921795367197/
https://www.mirror.co.uk/sport/football/match-reports/man-utd-vs-watford-live-21558426
https://thebusbybabe.sbnation.com/2020/2/23/21149691/player-ratings-manchester-united-3-0-watford
https://www.espn.co.uk/football/match/_/gameId/605777/watford-manchester-united
new match
https://www.espn.co.uk/football/match/_/gameId/605882/manchester-united-norwich-city
https://www.bbc.co.uk/sport/football/59529643
https://www.mufcinfo.com/manupag/match_data/match_sql.php?my_match_date=2021-12-11
https://www.canaries.co.uk/video-media/30513
https://www.theguardian.com/football/live/2021/dec/11/norwich-v-manchester-united-premier-league-live
https://www.premierleague.com/en/match/2210430/norwich-city-vs-manchester-united
https://www.premierleague.com/en/video/4360234/manchester-united-v-norwich-city-2021-22-full-match-replay
new match
https://www.wolves.co.uk/news/mens-first-team/20220205-report-wolves-0-1-norwich/
https://www.espn.co.uk/football/match/_/gameId/627172/norwich-city-wolverhampton-wanderers
https://www.premierleague.com/en/match/2210640/wolverhampton-wanderers-vs-norwich-city
https://www.canaries.co.uk/content/match-preview-wolves-v-norwich
https://www.youtube.com/watch?v=Qzj214kn8Ig
https://www.skysports.com/football/wolverhampton-wanderers-vs-norwich-city/teams/462179
https://www.facebook.com/craigbrown2011/posts/now-on-my-way-to-london-to-watch-norwich-city-play-afc-wimbledon-at-plough-lane-/10175367723405650/
https://www.bbc.co.uk/sport/football/60266419
https://www.espn.co.uk/football/report/_/gameId/627172
https://www.youtube.com/watch?v=6cX1iHtOgF8
new match
https://www.espn.co.uk/football/match/_/gameId/605698/norwich-city-aston-villa
https://www.avfc.co.uk/news/2022/april/30/aston-villa-v-norwich-city/
https://www.youtube.com/watch?v=n5fmQFvitaM
https://www.bbc.co.uk/sport/football/61198620
https://www.canaries.co.uk/content/match-report-v-aston-villa
https://www.theguardian.com/football/2022/apr/30/aston-villa-norwich-premier-league-match-report
https://www.youtube.com/watch?v=pIjDT_uRhD4
https://www.independent.co.uk/sport/football/norwich-aston-villa-result-final-score-report-dean-smith-b2069128.html
https://www.premierleague.com/en/match/1059883/aston-villa-vs-norwich-city
https://www.flashscore.com.au/match/football/aston-villa-W00wmLO0/norwich-Qo6off6p/report/?mid=tWZ0nkls
new match
https://www.wolves.co.uk/news/mens-first-team/20220515-report-wolves-1-1-norwich/
https://www.espn.co.uk/football/match/_/gameId/605678/norwich-city-wolverhampton-wanderers
https://www.canaries.co.uk/content/match-report-v-wolves
https://www.youtube.com/watch?v=Qzj214kn8Ig
https://www.premierleague.com/en/match/2210640/wolverhampton-wanderers-vs-norwich-city
https://www.theguardian.com/football/2022/may/15/wolves-norwich-premier-league-match-report
https://www.skysports.com/football/news/11095/12612008/wolves-1-1-norwich-honours-even-at-molineux-as-rayan-ait-nouri-gives-hosts-a-point
https://www.bbc.co.uk/sport/football/61368178
https://www.youtube.com/watch?v=5lv0PGDuoKQ
https://www.espn.co.uk/football/match/_/gameId/627172/norwich-city-wolverhampton-wanderers
new match
https://www.espn.co.uk/football/match/_/gameId/652266/aston-villa-manchester-united
https://www.manutd.com/en/news/match-report-and-highlights-for-man-utd-v-aston-villa-10-november-2022
https://www.espn.co.uk/football/match/_/gameId/637959/manchester-united-aston-villa
https://www.avfc.co.uk/news/2022/november/10/manchester-united-v-aston-villa/
https://www.whoscored.com/matches/1685971/show/england-league-cup-2022-2023-manchester-united-aston-villa
https://www.skysports.com/football/news/11095/12743896/man-utd-4-2-aston-villa-scott-mctominay-puts-seal-on-comeback-victory-in-crazy-carabao-cup-tie
https://www.tiktok.com/@manutd/video/7617557969600810262
https://www.premierleague.com/en/video/4360790/manchester-united-v-aston-villa-2022-23-full-match-replay
https://www.premierleague.com/en/match/2293148
new match
https://www.espn.co.uk/football/match/_/gameId/643716/norwich-city-west-bromwich-albion
https://www.youtube.com/watch?v=7F6MTyTd_eI
https://www.skysports.com/football/news/11688/12868157/west-brom-2-1-norwich-city-jed-wallace-winner-keeps-baggies-play-off-hopes-alive-and-ends-those-of-the-canaries
https://www.canaries.co.uk/video-media/32404
https://www.bbc.co.uk/sport/football/live/cg5djdj0mj9t
https://www.youtube.com/watch?v=EqV2OKV1gto
https://www.wba.co.uk/video-media/101868
https://www.reddit.com/r/NorwichCity/comments/1r4k39h/match_thread_norwich_city_v_west_bromwich_albion/
https://www.facebook.com/NorwichCityFootballClub/videos/highlights-west-brom-v-norwich-city/875245761443873/
https://www.canaries.co.uk/content/match-report-west-brom-0-5-norwich-city
new match
https://www.arsenal.com/
https://www.instagram.com/arsenal/?hl=en
https://en.wikipedia.org/wiki/Arsenal_F.C.
https://www.premierleague.com/en/clubs/3/arsenal/overview
https://x.com/Arsenal
https://www.bbc.co.uk/sport/football/teams/arsenal
https://www.youtube.com/@arsenal
https://www.theguardian.com/football/arsenal
https://www.espn.co.uk/football/team/_/id/359
new match
https://www.arsenal.com/news/report-west-ham-united-0-6-arsenal-alQgU1x5QMQ4
https://www.espn.co.uk/football/match/_/gameId/671261/arsenal-west-ham-united
https://www.bbc.co.uk/sport/football/live/crkpe566737t
https://www.whufc.com/en/news/arsenal-hit-west-ham-united-six
https://www.theguardian.com/football/live/2024/feb/11/west-ham-v-arsenal-premier-league-live
https://www.whoscored.com/matches/1821427/show/england-premier-league-2024-2025-arsenal-west-ham
https://www.bbc.co.uk/sport/football/videos/c3d2859pm80o
https://www.facebook.com/Arsenal/videos/highlights-west-ham-0-6-arsenal/741587937914507/
https://arseblog.com/2026/05/west-ham-0-1-arsenal-no-headline-can-do-it-justice/
new match
https://www.espn.co.uk/football/match/_/gameId/671337/manchester-united-chelsea
https://www.manutd.com/en/news/match-report-chelsea-v-man-utd-premier-league-4-april-2024
https://www.chelseafc.com/en/match/chelsea-vs-manchester-united-english-premier-league-2024-04-04
https://www.premierleague.com/en/match/2367844
https://www.theguardian.com/football/2024/apr/04/chelsea-manchester-united-premier-league-match-report
https://www.facebook.com/chelseafcw/posts/full-match-report-chelsea-2-0-manchester-united-%EF%B8%8F%EF%B8%8F/1498508871637149/
https://mufcinfo.com/manupag/match_data/match_sql.php?my_match_date=2024-04-04
https://en.wikipedia.org/wiki/2024%E2%80%9325_Manchester_United_F.C._season
new match
https://www.chelseafc.com/en/match/chelsea-vs-barrow-english-league-cup-2024-09-24
https://www.espn.co.uk/football/match/_/gameId/720277/barrow-chelsea
https://www.bbc.co.uk/sport/football/live/c62d7j5j42rt
https://www.youtube.com/watch?v=YcmZf1FP-6U
https://www.365scores.com/football/match/efl-cup-9/barrow-chelsea-101-106-9
https://www.independent.co.uk/sport/football/chelsea-barrow-live-stream-result-score-2024-b2618250.html
https://www.youtube.com/watch?v=7J3YWyux2_I
https://www.footballcritic.com/football-league-cup-chelsea-fc-barrow-afc/match-report/3514902
https://www.oddsivio.com/matches/29465
https://www.theguardian.com/football/live/2024/sep/24/chelsea-barrow-manchester-city-watford-walsall-leicester-wycombe-aston-villa-carabao-cup-live
new match
https://www.skysports.com/football/news/11661/13454960/man-utd-4-2-brighton-matheus-cunha-scores-first-goal-as-ruben-amorims-side-continue-momentum-with-third-straight-premier-league-win
https://www.espn.co.uk/football/report/_/gameId/740683
https://www.manutd.com/en/news/match-report-for-man-utd-v-brighton-in-the-premier-league-25-october-2025
https://www.premierleague.com/en/match/2561982/manchester-united-vs-brighton-and-hove-albion
https://www.facebook.com/theoptaanalyst/posts/manchester-united-4-2-brightonman-utd-made-it-three-wins-in-a-row-in-the-premier/1222983396524600/
https://www.mufcinfo.com/manupag/match_data/match_sql.php?my_match_date=2025-10-25
https://www.reddit.com/r/ManchesterUnited/comments/1qa6y5k/post_match_thread_manchester_united_1_2_brighton/
https://www.theguardian.com/football/live/2025/oct/25/manchester-united-v-brighton-premier-league-live-updates
new match
https://www.premierleague.com/en/match/2562051/manchester-united-vs-bournemouth
https://www.manutd.com/en/news/match-report-man-utd-bournemouth-premier-league-15-december-2025
https://www.espn.co.uk/football/match/_/gameId/740751/afc-bournemouth-manchester-united
https://www.bbc.co.uk/sport/football/live/c4g6jvj3d75t
https://www.theguardian.com/football/live/2025/dec/15/manchester-united-v-bournemouth-premier-league-updates-live
https://www.youtube.com/watch?v=aQtdKmzWAbI
https://fbref.com/en/matches/fe812068/Manchester-United-Bournemouth-December-15-2025-Premier-League
https://www.reddit.com/r/reddevils/comments/1pnkedd/post_match_thread_manchester_united_44_afc/
https://www.footballcritic.com/premier-league-manchester-united-fc-afc-bournemouth/preview/3739698
https://www.skysports.com/football/news/11095/13482198/man-utd-4-4-bournemouth-ruben-amorims-experimental-side-held-to-thrilling-draw-by-cherries
new match

In [9]:
# Read text from an articles

import requests
from bs4 import BeautifulSoup
import re

def extract_article(url):
    html = requests.get(url).text               # Gets the raw HTML code of the webpage
    soup = BeautifulSoup(html, "html.parser")   # Parses the HTML code into paragraphs/heading/etc. by looking for <p>/<h1>/etc.

    paragraphs = [p.get_text() for p in soup.find_all("p")]     # Gets all paragraph text
    text = "\n".join(paragraphs)
    text = re.sub(r"\s+", " ", text)             # Find all chunks of whitespace and replace them with a single space. \s is any whitespace character. \s+ means more than one in a row
    return text.strip()

# Testing the function

#extract_article("http://news.bbc.co.uk/sport2/hi/football/eng_prem/7163892.stm")

In [10]:
import trafilatura

def extract_article(url):
    downloaded = trafilatura.fetch_url(url)
    text = trafilatura.extract(downloaded)
    return text

In [11]:
# Determine the source of an article from the url found by the Google search

from urllib.parse import urlparse

# A set of all trusted sources: aim is that found urls will include one of these within domain name
# NEEDS UPDATING TO INCLUDE MORE SOURCES
trusted_sources = {
    "bbc",
    "espn",
    "skysports",
    "guardian"
}
# trusted_sources = {
#     "bbc",
#     "skysports",
#     "espn",
#     "rte"
# }

def get_source(url):
    domain = urlparse(url).netloc.lower()               # netloc extracts the network location: i.e. "https://www.example.com:8080/page" goes to "www.example.com:8080"
    for name in trusted_sources:
        if name in domain:                              # Check if one of the trusted sources is in the domain name
            return name
    return "other"

# Testing the function
get_source("http://news.bbc.co.uk/sport2/hi/football/eng_prem/7163892.stm")

'bbc'

In [12]:
# Build article records into a Dataframe

# Create a list with an entry for each article from a trusted source for each match
article_records = []
for _, row in df.iterrows():                        # iterrows() iterates through tuples (*,*) of row index and corresponding one row Dataframe
    match_id = row["match_id"]
    urls = row["article urls"]
    for url in urls:
        source = get_source(url)

        # Add source, url and text for each trusted article for a given match
        if source in trusted_sources:
            text = extract_article(url)[:32750]   # Limit the number of characters in the text: Excel can only store up to approx 32750 characters before going to a new cell
            article_records.append({
                "match_id":match_id,
                "source":source,
                "url": url,
                "text": text
            })

# Convert data to a dataframe and store into a csv file
article_df = pd.DataFrame(article_records)
article_df.to_csv("../data/articles.csv", index=False)