In [1]:
import json

with open("../data/match.json") as f:
    data = json.load(f)

data

[{'Home team': 'Man United',
  'Away team': 'Birmingham',
  'Final score': '1-0',
  'Ground': 'Old Trafford',
  'goals': [{'minute': '25',
    'player': 'Carlos Tevez',
    'team': 'Man United',
    'evidence': 'Tevez scored the only goal as Manchester United secured a narrow victory... Tevez... calmly slotted home the winner on 25 minutes.'}],
  'red_cards': [],
  'home_manager': 'Sir Alex Ferguson',
  'home_manager_evidence': 'United manager Sir Alex Ferguson, sat in the stands to serve out his two-match touchline ban...',
  'away_manager': 'Alex McLeish',
  'away_manager_evidence': 'Birmingham boss Alex McLeish - once a protege of Ferguson in their days together at Aberdeen...',
  'man_of_the_match': 'Carlos Tevez',
  'man_of_the_match_evidence': "BBC Sport Player Rater man of the match: Manchester United's Carlos Tevez 8.15"},
 {'Home team': 'Man United',
  'Away team': 'Hull',
  'Final score': '4-3',
  'Ground': 'Old Trafford',
  'goals': [{'minute': '3',
    'player': 'Cristiano Ronaldo',
    'team': 'Man United',
    'evidence': 'Ronaldo picked out a team-mate despite looking in the other direction.'},
   {'minute': '29',
    'player': 'Michael Carrick',
    'team': 'Man United',
    'evidence': 'Carrick, whose precise low strike with his left foot also went in off the post.'},
   {'minute': '44',
    'player': 'Cristiano Ronaldo',
    'team': 'Man United',
    'evidence': "Ronaldo headed the third from Nani's corner."},
   {'minute': '57',
    'player': 'Nemanja Vidic',
    'team': 'Man United',
    'evidence': 'Vidic low down and he guided the ball past Myhill.'},
   {'minute': '75',
    'player': 'Bernard Mendy',
    'team': 'Hull',
    'evidence': 'Substitute Mendy brilliantly lobbed the ball over the advancing Van der Sar.'},
   {'minute': '90',
    'player': 'Geovanni',
    'team': 'Hull',
    'evidence': 'Geovanni made no mistake from the spot.'}],
  'red_cards': [],
  'home_manager': 'Sir Alex Ferguson',
  'home_manager_evidence': "Phelan hails 'fantastic' game",
  'away_manager': 'Phil Brown',
  'away_manager_evidence': 'We gave Man Utd too much respect - Brown',
  'man_of_the_match': 'Cristiano Ronaldo',
  'man_of_the_match_evidence': 'Ronaldo has scored twice in each of his last two games.'},
 {'Home team': 'Aston Villa',
  'Away team': 'Wycombe',
  'Final score': '2-0',
  'Ground': 'Villa Park',
  'goals': [{'minute': "75'",
    'player': 'Ciaran Clark',
    'team': 'Aston Villa',
    'evidence': 'Ciaran Clark opened the scoring for Villa when he headed in an Ashley Westwood cross.'},
   {'minute': "90'",
    'player': 'Idrissa Gueye',
    'team': 'Aston Villa',
    'evidence': 'Idrissa Gueye guided in a second to ensure the hosts progressed.'}],
  'red_cards': [],
  'home_manager': 'Remi Garde',
  'home_manager_evidence': 'Aston Villa manager Remi Garde: "The most important thing was to win and go through. We\'ve been professional."',
  'away_manager': 'Gareth Ainsworth',
  'away_manager_evidence': 'Wycombe boss Gareth Ainsworth: "We\'ve got players who are destined for bigger things and, when they put in a performance like that, it makes me a proud man."',
  'man_of_the_match': '',
  'man_of_the_match_evidence': ''},
 {'Home team': 'Man United',
  'Away team': 'Celta Vigo',
  'Final score': '1-1',
  'Ground': 'Old Trafford',
  'goals': [{'minute': '67',
    'player': 'Marcus Rashford',
    'team': 'Man United',
    'evidence': 'GOAL! Celta 0-1 United (Rashford 67)'}],
  'red_cards': [{'minute': '87',
    'player': 'Eric Bailly',
    'team': 'Man United',
    'evidence': 'Bailly was sent off for a swipe at former Manchester City striker Guidetti'},
   {'minute': '88',
    'player': 'Facundo Roncaglia',
    'team': 'Celta Vigo',
    'evidence': 'Roncaglia dismissed for retaliating.'}],
  'home_manager': 'Jose Mourinho',
  'home_manager_evidence': '"We were the best team in the first leg but we never kill, we never score goals related to the chances we have."',
  'away_manager': '',
  'away_manager_evidence': '',
  'man_of_the_match': 'Marouane Fellaini',
  'man_of_the_match_evidence': 'Man of the match - Marouane Fellani (Manchester United)'},
 {'Home team': 'Man United',
  'Away team': 'Bournemouth',
  'Final score': '1-0',
  'Ground': 'Old Trafford',
  'goals': [{'minute': '25',
    'player': 'Romelu Lukaku',
    'team': 'Man United',
    'evidence': 'Romelu Lukaku (25) silenced his critics with the winning strike midway through the first-half.'}],
  'red_cards': [],
  'home_manager': 'Jose Mourinho',
  'home_manager_evidence': 'Jose Mourinho: "When you lose a match it\'s important you don\'t lose two in a row."',
  'away_manager': 'Eddie Howe',
  'away_manager_evidence': 'Eddie Howe: "They have an outstanding goalkeeper who made a number of good saves..."',
  'man_of_the_match': 'David de Gea',
  'man_of_the_match_evidence': 'Man of the match: David de Gea'},
 {'Home team': 'Man United',
  'Away team': 'Brighton',
  'Final score': '3-1',
  'Ground': 'Old Trafford',
  'goals': [{'minute': '19',
    'player': 'Davy Propper',
    'team': 'Brighton',
    'evidence': "Davy Propper's own goal saw Manchester United take a 2-0 lead in the 19th minute."},
   {'minute': '',
    'player': 'Andreas Pereira',
    'team': 'Man United',
    'evidence': 'Midfielder Andreas Pereira and striker Marcus Rashford scored either side of a Davy Propper own goal.'},
   {'minute': '',
    'player': 'Marcus Rashford',
    'team': 'Man United',
    'evidence': 'Midfielder Andreas Pereira and striker Marcus Rashford scored either side of a Davy Propper own goal.'}],
  'red_cards': [],
  'home_manager': 'Ole Gunnar Solskjaer',
  'home_manager_evidence': "Ole Gunnar Solskjaer described Manchester United's 3-1 win over Brighton as 'their best performance of the season'.",
  'away_manager': 'Graham Potter',
  'away_manager_evidence': "Brighton manager Graham Potter, also to Match of the Day: 'They deserved to win the game, if you make any mistake they can turn defence into attack so quickly.'",
  'man_of_the_match': 'Fred',
  'man_of_the_match_evidence': 'Man of the match - Fred (Manchester United)'},
 {'Home team': 'Man United',
  'Away team': 'Aston Villa',
  'Final score': '2-2',
  'Ground': 'Old Trafford',
  'goals': [{'minute': 'N/A',
    'player': 'Jack Grealish',
    'team': 'Aston Villa',
    'evidence': 'Grealish opened the scoring with a peach of a strike.'},
   {'minute': 'N/A',
    'player': 'Marcus Rashford',
    'team': 'Man United',
    'evidence': 'Rashford...that was 1-1.'},
   {'minute': 'N/A',
    'player': 'Victor Lindelöf',
    'team': 'Man United',
    'evidence': 'Victor Lindelöf headed in.'},
   {'minute': 'N/A',
    'player': 'Tyrone Mings',
    'team': 'Aston Villa',
    'evidence': 'that was the equaliser.'}],
  'red_cards': [],
  'home_manager': 'Ole Gunnar Solskjær',
  'home_manager_evidence': 'But for Ole Gunnar Solskjær the bottom line is that United have won only four of 14 league games this season.',
  'away_manager': 'Dean Smith',
  'away_manager_evidence': 'Smith was left praising the excellent Grealish.',
  'man_of_the_match': 'Jack Grealish',
  'man_of_the_match_evidence': 'Smith was left praising the excellent Grealish.'},
 {'Home team': 'Leicester',
  'Away team': 'Norwich',
  'Final score': '1-1',
  'Ground': 'King Power Stadium',
  'goals': [{'minute': '25th',
    'player': 'Teemu Pukki',
    'team': 'Norwich',
    'evidence': 'Norwich had taken the lead through Teemu Pukki’s latest ice-cool finish.'},
   {'minute': '37th',
    'player': 'Tim Krul',
    'team': 'Norwich',
    'evidence': "Jamie Vardy's bullet header was turned into the net by Norwich keeper Tim Krul."}],
  'red_cards': [],
  'home_manager': 'Brendan Rodgers',
  'home_manager_evidence': 'Brendan Rodgers says he is not thinking about the growing gap behind league leaders Liverpool.',
  'away_manager': 'Daniel Farke',
  'away_manager_evidence': 'Daniel Farke: "The goal was a fantastic pass and finish."',
  'man_of_the_match': 'Caglar Soyuncu',
  'man_of_the_match_evidence': 'Man of the match - Caglar Soyuncu (Leicester)'},
 {'Home team': 'Man United',
  'Away team': 'Watford',
  'Final score': '3-0',
  'Ground': 'Old Trafford',
  'goals': [{'minute': 'unknown',
    'player': 'Bruno Fernandes',
    'team': 'Man United',
    'evidence': 'Fernandes took this with the swagger United have missed in recent years: an odd-looking hop straight up in the air sent Foster to his right before he slotted a first goal for United.'},
   {'minute': 'unknown',
    'player': 'Anthony Martial',
    'team': 'Man United',
    'evidence': 'What came next was a Martial special... Martial performed a drag-back that left the Watford player a spectator before, from under Foster’s nose, he chipped a third goal.'},
   {'minute': 'unknown',
    'player': 'Mason Greenwood',
    'team': 'Man United',
    'evidence': 'Yet Greenwood’s emphatic strike, pin-balling off the frame of the goal, sent United and their fans home even more content.'}],
  'red_cards': [],
  'home_manager': 'Ole Gunnar Solskjær',
  'home_manager_evidence': '“I hope [we can beat them] because there are four big league games coming up – Everton, Manchester City, Tottenham and Sheffield United,” Ole Gunnar Solskjær said.',
  'away_manager': 'Nigel Pearson',
  'away_manager_evidence': 'while Nigel Pearson’s only adjustment from a draw at Brighton 15 days ago was a preference for Craig Dawson in place of Adrian Mariappa.',
  'man_of_the_match': 'Bruno Fernandes',
  'man_of_the_match_evidence': 'Each have the quality Manchester United require to challenge for a Champions League place, this win lifting them up two places to fifth.'},
 {'Home team': 'Norwich',
  'Away team': 'Man United',
  'Final score': '0-1',
  'Ground': 'Carrow Road',
  'goals': [{'minute': '75',
    'player': 'Cristiano Ronaldo',
    'team': 'Man United',
    'evidence': "Cristiano Ronaldo's penalty earned Manchester United a narrow victory over Norwich."}],
  'red_cards': [],
  'home_manager': 'Dean Smith',
  'home_manager_evidence': 'Injury, ineligibility and illness forced Norwich boss Dean Smith into five changes to the side that lost at Tottenham last week.',
  'away_manager': 'Ralf Rangnick',
  'away_manager_evidence': 'Ralf Rangnick restored the XI that beat Crystal Palace in his first game in charge last weekend.',
  'man_of_the_match': 'Cristiano Ronaldo',
  'man_of_the_match_evidence': 'Ronaldo rescues United'},
 {'Home team': 'Wolves',
  'Away team': 'Norwich',
  'Final score': '0-1',
  'Ground': 'Molineux',
  'goals': [{'minute': "45'+1",
    'player': 'Kenny McLean',
    'team': 'Norwich',
    'evidence': 'Kenny McLean scored a first-half winner as Norwich beat fellow Premier League side Wolves.'}],
  'red_cards': [],
  'home_manager': 'Bruno Lage',
  'home_manager_evidence': "Bruno Lages' side could not equalise.",
  'away_manager': 'Dean Smith',
  'away_manager_evidence': 'Dean Smith has galvanised Norwich since taking over in November.',
  'man_of_the_match': 'Kenny McLean',
  'man_of_the_match_evidence': 'Kenny McLean scored a first-half winner as Norwich beat fellow Premier League side Wolves.'},
 {'Home team': 'Aston Villa',
  'Away team': 'Norwich',
  'Final score': '2-0',
  'Ground': 'Villa Park',
  'goals': [{'minute': 'first half',
    'player': 'Ollie Watkins',
    'team': 'Aston Villa',
    'evidence': 'Ollie Watkins put Villa ahead in the first half, capitalising on a slip from Brandon Williams before lashing high into the net.'},
   {'minute': 'stoppage time',
    'player': 'Danny Ings',
    'team': 'Aston Villa',
    'evidence': "Danny Ings added a late goal in stoppage time to add to Norwich's misery."}],
  'red_cards': [],
  'home_manager': 'Steven Gerrard',
  'home_manager_evidence': 'Manager Steven Gerrard handed a full debut to 18-year-old England Under-19 midfielder Tim Iroegbunam, who was solid in a holding role.',
  'away_manager': 'Dean Smith',
  'away_manager_evidence': 'Manager Dean Smith said "plans are already in place" for their bid to return to the top flight.',
  'man_of_the_match': 'Ollie Watkins',
  'man_of_the_match_evidence': 'Watkins was a livewire all day, volleying just over in the sixth minute and constantly threatening to get in behind.'},
 {'Home team': 'Wolves',
  'Away team': 'Norwich',
  'Final score': '1-1',
  'Ground': 'Molineax',
  'goals': [{'minute': '37th',
    'player': 'Teemu Pukki',
    'team': 'Norwich',
    'evidence': "Pukki took full advantage by dribbling into the box and firing a low shot through the Wolves captain's legs."},
   {'minute': '55th',
    'player': 'Rayan Aït-Nouri',
    'team': 'Wolves',
    'evidence': 'Ait-Nouri cleverly cushioned a header into the far corner.'}],
  'red_cards': [],
  'home_manager': 'Bruno Lage',
  'home_manager_evidence': "Lage's team now unable to catch West Ham in seventh.",
  'away_manager': 'Dean Smith',
  'away_manager_evidence': "Dean Smith said of his Norwich side’s display: 'I enjoyed it, it was a good disciplined performance.'",
  'man_of_the_match': 'Teemu Pukki',
  'man_of_the_match_evidence': 'The Finland international was a thorn in the Wolves defence all afternoon long.'},
 {'Home team': 'Man United',
  'Away team': 'Aston Villa',
  'Final score': '4-2',
  'Ground': 'Old Trafford',
  'goals': [{'minute': "49'",
    'player': 'Anthony Martial',
    'team': 'Man United',
    'evidence': "Anthony Martial - 49'"},
   {'minute': "67'",
    'player': 'Marcus Rashford',
    'team': 'Man United',
    'evidence': "Marcus Rashford - 67'"},
   {'minute': "78'",
    'player': 'Bruno Fernandes',
    'team': 'Man United',
    'evidence': "Bruno Fernandes - 78'"},
   {'minute': "90'+1'",
    'player': 'Scott McTominay',
    'team': 'Man United',
    'evidence': "Scott McTominay - 90'+1'"},
   {'minute': "48'",
    'player': 'Ollie Watkins',
    'team': 'Aston Villa',
    'evidence': "Ollie Watkins - 48'"},
   {'minute': "61'",
    'player': 'Diogo Dalot',
    'team': 'Aston Villa',
    'evidence': "Diogo Dalot - 61' OG"}],
  'red_cards': [],
  'home_manager': 'Erik ten Hag',
  'home_manager_evidence': "Erik ten Hag's side falling behind twice before Bruno Fernandes' deflected strike put them ahead for the first time",
  'away_manager': 'Unai Emery',
  'away_manager_evidence': "Unai Emery's side had twice led in the tie",
  'man_of_the_match': 'Scott McTominay',
  'man_of_the_match_evidence': 'Scott McTominay puts seal on comeback victory in crazy Carabao Cup tie.'},
 {'Home team': 'West Brown',
  'Away team': 'Norwich',
  'Final score': '2-1',
  'Ground': 'Hawthorns',
  'goals': [{'minute': '41',
    'player': 'Josh Sargent',
    'team': 'Norwich',
    'evidence': "Josh Sargent's clinical finish - his second goal in four games - gave Norwich the lead after 41 minutes."},
   {'minute': '45+1',
    'player': 'Conor Townsend',
    'team': 'West Brom',
    'evidence': 'Conor Townsend curled in a sparkling free-kick in first-half stoppage time.'},
   {'minute': '',
    'player': 'Jed Wallace',
    'team': 'West Brom',
    'evidence': 'Jed Wallace scored what proved to be the winner, when he diverted a cross from Townsend past Angus Gunn.'}],
  'red_cards': [],
  'home_manager': 'Carlos Corberan',
  'home_manager_evidence': 'Baggies boss Carlos Corberan took the opportunity to bring on Jake Livermore for what could be his final appearance for the club.',
  'away_manager': 'David Wagner',
  'away_manager_evidence': "Norwich's David Wagner: 'In the second half, we lost our structure. We were not calm enough and we didn't look mature.'",
  'man_of_the_match': 'Conor Townsend',
  'man_of_the_match_evidence': 'Player of the match - Conor Townsend.'},
 {'Home team': 'Arsenal',
  'Away team': 'Man United',
  'Final score': '3-1',
  'Ground': 'Emirates Stadium',
  'goals': [{'minute': 'unknown',
    'player': 'Marcus Rashford',
    'team': 'Man United',
    'evidence': 'Marcus Rashford scored for Man United.'},
   {'minute': 'unknown',
    'player': 'Martin Ødegaard',
    'team': 'Arsenal',
    'evidence': 'Martin Ødegaard scored for Arsenal.'},
   {'minute': 'unknown',
    'player': 'Declan Rice',
    'team': 'Arsenal',
    'evidence': 'Declan Rice scored for Arsenal.'},
   {'minute': 'unknown',
    'player': 'Gabriel Jesus',
    'team': 'Arsenal',
    'evidence': 'Gabriel Jesus scored for Arsenal.'}],
  'red_cards': [],
  'home_manager': '',
  'home_manager_evidence': '',
  'away_manager': '',
  'away_manager_evidence': '',
  'man_of_the_match': '',
  'man_of_the_match_evidence': ''},
 {'Home team': 'West Ham',
  'Away team': 'Arsenal',
  'Final score': '0-6',
  'Ground': 'Olympic Stadium',
  'goals': [{'minute': '32',
    'player': 'William Saliba',
    'team': 'Arsenal',
    'evidence': 'GOAL! West Ham 0-1 Arsenal (Saliba 32)'},
   {'minute': '41',
    'player': 'Bukayo Saka',
    'team': 'Arsenal',
    'evidence': 'GOAL! West Ham 0-2 Arsenal (Saka 41 pen)'},
   {'minute': '44',
    'player': 'Gabriel',
    'team': 'Arsenal',
    'evidence': 'GOAL! West Ham 0-3 Arsenal (Gabriel 44)'},
   {'minute': '45+2',
    'player': 'Leandro Trossard',
    'team': 'Arsenal',
    'evidence': 'GOAL! West Ham 0-4 Arsenal (Trossard 45+2)'},
   {'minute': '63',
    'player': 'Bukayo Saka',
    'team': 'Arsenal',
    'evidence': 'GOAL! West Ham 0-5 Arsenal (Saka 63)'},
   {'minute': '66',
    'player': 'Declan Rice',
    'team': 'Arsenal',
    'evidence': 'GOAL! West Ham 0-6 Arsenal (Rice 66)'}],
  'red_cards': [],
  'home_manager': 'David Moyes',
  'home_manager_evidence': '“Look I don’t mean to criticise Moyes who lifted West Ham from the bottom three,” sys Yash Gupta.',
  'away_manager': 'Mikel Arteta',
  'away_manager_evidence': '“It was a brilliant performance - we controlled everything and were really sharp in front of goal.”',
  'man_of_the_match': 'Bukayo Saka',
  'man_of_the_match_evidence': '“I’m proud to score 50 goals for Arsenal but I can’t be completely happy when I miss chances like I did today.”'},
 {'Home team': 'Chelsea',
  'Away team': 'Man United',
  'Final score': '4-3',
  'Ground': 'Stamford Bridge',
  'goals': [{'minute': '6',
    'player': 'Cole Palmer',
    'team': 'Chelsea',
    'evidence': 'Cole Palmer had scored the first to put Chelsea 2-0 up'},
   {'minute': '99',
    'player': 'Cole Palmer',
    'team': 'Chelsea',
    'evidence': 'his hat-trick goal deflecting in off the United substitute Scott McTominay'},
   {'minute': '',
    'player': 'Alejandro Garnacho',
    'team': 'Man United',
    'evidence': 'Garnacho to head past Djordje Petrovic on the bounce.'},
   {'minute': '',
    'player': 'Bruno Fernandes',
    'team': 'Man United',
    'evidence': 'Fernandes guided his header home.'},
   {'minute': '',
    'player': 'Conor Gallagher',
    'team': 'Chelsea',
    'evidence': 'Conor Gallagher to sweep past André Onana.'}],
  'red_cards': [],
  'home_manager': 'Mauricio Pochettino',
  'home_manager_evidence': 'Mauricio Pochettino and his players will hope it proves a turning point for them.',
  'away_manager': 'Erik ten Hag',
  'away_manager_evidence': 'the pressure on Erik ten Hag, too, should there have been any further scope for that.',
  'man_of_the_match': 'Cole Palmer',
  'man_of_the_match_evidence': 'Palmer was the shining star, close to unplayable for most of the game.'},
 {'Home team': 'Chelsea',
  'Away team': 'Barrow',
  'Final score': '5-0',
  'Ground': 'Stamford Bridge',
  'goals': [{'minute': "8'",
    'player': 'Christopher Nkunku',
    'team': 'Chelsea',
    'evidence': 'Nkunku opened the scoring in the eighth minute with a cool finish after a fine chipped pass from Joao Felix.'},
   {'minute': "15'",
    'player': 'Christopher Nkunku',
    'team': 'Chelsea',
    'evidence': 'A low Malo Gusto cross from the right glanced into the bottom left, and it’s a second goal for Christopher Nkunku.'},
   {'minute': "28'",
    'player': 'Paul Farman',
    'team': 'Barrow',
    'evidence': 'A free kick for Chelsea... off the post, and in off the back of the unfortunate Paul Farman.'},
   {'minute': "48'",

In [2]:
# Code that produces first Excel spreadsheet (match level data)

import pandas as pd

match_rows = []
for match in data:
    match_rows.append({
        "home team": match["Home team"],
        "home manager": match["home_manager"],
        "home score": match["Final score"].split("-")[0],
        "away team": match["Away team"],
        "away manager": match["away_manager"],
        "away score": match["Final score"].split("-")[1],
        "stadium": match["Ground"]
    })
matches_df = pd.DataFrame(match_rows)
matches_df

,home team,home manager,home score,away team,away manager,away score,stadium
0,Man United,Sir Alex Ferguson,1,Birmingham,Alex McLeish,0,Old Trafford
1,Man United,Sir Alex Ferguson,4,Hull,Phil Brown,3,Old Trafford
2,Aston Villa,Remi Garde,2,Wycombe,Gareth Ainsworth,0,Villa Park
3,Man United,Jose Mourinho,1,Celta Vigo,,1,Old Trafford
4,Man United,Jose Mourinho,1,Bournemouth,Eddie Howe,0,Old Trafford
5,Man United,Ole Gunnar Solskjaer,3,Brighton,Graham Potter,1,Old Trafford
6,Man United,Ole Gunnar Solskjær,2,Aston Villa,Dean Smith,2,Old Trafford
7,Leicester,Brendan Rodgers,1,Norwich,Daniel Farke,1,King Power Stadium
8,Man United,Ole Gunnar Solskjær,3,Watford,Nigel Pearson,0,Old Trafford
9,Norwich,Dean Smith,0,Man United,Ralf Rangnick,1,Carrow Road
10,Wolves,Bruno Lage,0,Norwich,Dean Smith,1,Molineux
11,Aston Villa,Steven Gerrard,2,Norwich,Dean Smith,0,Villa Park
12,Wolves,Bruno Lage,1,Norwich,Dean Smith,1,Molineax
13,Man United,Erik ten Hag,4,Aston Villa,Unai Emery,2,Old Trafford
14,West Brown,Carlos Corberan,2,Norwich,David Wagner,1,Hawthorns
15,Arsenal,,3,Man United,,1,Emirates Stadium
16,West Ham,David Moyes,0,Arsenal,Mikel Arteta,6,Olympic Stadium
17,Chelsea,Mauricio Pochettino,4,Man United,Erik ten Hag,3,Stamford Bridge
18,Chelsea,Enzo Maresca,5,Barrow,,0,Stamford Bridge
19,Man United,Ruben Amorim,4,Brighton,Fabian Hurzeler,2,Old Trafford
20,Man United,Ruben Amorim,4,Bournemouth,Andoni Iraola,4,Old Trafford

In [3]:
def summarise_goals(goals):
    return ", ".join([
        f"{g['player']} ({g['minute']})"
        for g in goals
    ])

matches_df["goals_summary"] = [
    summarise_goals(match.get("goals", []))
    for match in data
]

matches_df

,home team,home manager,home score,away team,away manager,away score,stadium,goals_summary
0,Man United,Sir Alex Ferguson,1,Birmingham,Alex McLeish,0,Old Trafford,Carlos Tevez (25)
1,Man United,Sir Alex Ferguson,4,Hull,Phil Brown,3,Old Trafford,"Cristiano Ronaldo (3), Michael Carrick (29), C..."
2,Aston Villa,Remi Garde,2,Wycombe,Gareth Ainsworth,0,Villa Park,"Ciaran Clark (75'), Idrissa Gueye (90')"
3,Man United,Jose Mourinho,1,Celta Vigo,,1,Old Trafford,Marcus Rashford (67)
4,Man United,Jose Mourinho,1,Bournemouth,Eddie Howe,0,Old Trafford,Romelu Lukaku (25)
5,Man United,Ole Gunnar Solskjaer,3,Brighton,Graham Potter,1,Old Trafford,"Davy Propper (19), Andreas Pereira (), Marcus ..."
6,Man United,Ole Gunnar Solskjær,2,Aston Villa,Dean Smith,2,Old Trafford,"Jack Grealish (N/A), Marcus Rashford (N/A), Vi..."
7,Leicester,Brendan Rodgers,1,Norwich,Daniel Farke,1,King Power Stadium,"Teemu Pukki (25th), Tim Krul (37th)"
8,Man United,Ole Gunnar Solskjær,3,Watford,Nigel Pearson,0,Old Trafford,"Bruno Fernandes (unknown), Anthony Martial (un..."
9,Norwich,Dean Smith,0,Man United,Ralf Rangnick,1,Carrow Road,Cristiano Ronaldo (75)
10,Wolves,Bruno Lage,0,Norwich,Dean Smith,1,Molineux,Kenny McLean (45'+1)
11,Aston Villa,Steven Gerrard,2,Norwich,Dean Smith,0,Villa Park,"Ollie Watkins (first half), Danny Ings (stoppa..."
12,Wolves,Bruno Lage,1,Norwich,Dean Smith,1,Molineax,"Teemu Pukki (37th), Rayan Aït-Nouri (55th)"
13,Man United,Erik ten Hag,4,Aston Villa,Unai Emery,2,Old Trafford,"Anthony Martial (49'), Marcus Rashford (67'), ..."
14,West Brown,Carlos Corberan,2,Norwich,David Wagner,1,Hawthorns,"Josh Sargent (41), Conor Townsend (45+1), Jed ..."
15,Arsenal,,3,Man United,,1,Emirates Stadium,"Marcus Rashford (unknown), Martin Ødegaard (un..."
16,West Ham,David Moyes,0,Arsenal,Mikel Arteta,6,Olympic Stadium,"William Saliba (32), Bukayo Saka (41), Gabriel..."
17,Chelsea,Mauricio Pochettino,4,Man United,Erik ten Hag,3,Stamford Bridge,"Cole Palmer (6), Cole Palmer (99), Alejandro G..."
18,Chelsea,Enzo Maresca,5,Barrow,,0,Stamford Bridge,"Christopher Nkunku (8'), Christopher Nkunku (1..."
19,Man United,Ruben Amorim,4,Brighton,Fabian Hurzeler,2,Old Trafford,"Matheus Cunha (24), Casemiro (34), Bryan Mbeum..."
20,Man United,Ruben Amorim,4,Bournemouth,Andoni Iraola,4,Old Trafford,"Amad Diallo (13), Evanilson (46), Marcus Taver..."

In [4]:
from collections import Counter

goal_scorers = []
for match in data:
    for goal in match.get("goals", []):
        goal_scorers.append(goal["player"])

counts = Counter(goal_scorers)

ranking_df = (
    pd.DataFrame(
        counts.items(),
        columns=["Player", "Goals Seen Live"]
    )
    .sort_values(
        ["Goals Seen Live", "Player"],
        ascending=[False, True]
    )
)

ranking_df["Rank"] = (
    ranking_df["Goals Seen Live"]
    .rank(method="min", ascending=False)
    .astype(int)
)

ranking_df = ranking_df[
    ["Rank", "Player", "Goals Seen Live"]
].reset_index(drop=True)

ranking_df

    Rank                 Player  Goals Seen Live
0      1        Marcus Rashford                5
1      2        Bruno Fernandes                4
2      3     Christopher Nkunku                3
3      3      Cristiano Ronaldo                3
4      5        Anthony Martial                2
5      5           Bryan Mbeumo                2
6      5            Bukayo Saka                2
7      5            Cole Palmer                2
8      5            Declan Rice                2
9      5          Matheus Cunha                2
10     5          Ollie Watkins                2
11     5            Teemu Pukki                2
12    13     Alejandro Garnacho                1
13    13            Amad Diallo                1
14    13        Andreas Pereira                1
15    13          Bernard Mendy                1
16    13           Carlos Tevez                1
17    13               Casemiro                1
18    13  Charalampos Kostoulas                1
19    13           Ciaran Clark                1
20    13        Conor Gallagher                1
21    13         Conor Townsend                1
22    13             Danny Ings                1
23    13          Danny Welbeck                1
24    13           Davy Propper                1
25    13            Diogo Dalot                1
26    13      Eli Junior Kroupi                1
27    13              Evanilson                1
28    13                Gabriel                1
29    13          Gabriel Jesus                1
30    13               Geovanni                1
31    13          Idrissa Gueye                1
32    13          Jack Grealish                1
33    13            Jed Wallace                1
34    13           Josh Sargent                1
35    13           Kenny McLean                1
36    13       Leandro Trossard                1
37    13       Marcus Tavernier                1
38    13        Martin Ødegaard                1
39    13        Mason Greenwood                1
40    13        Michael Carrick                1
41    13          Nemanja Vidic                1
42    13            Paul Farman                1
43    13             Pedro Neto                1
44    13        Rayan Aït-Nouri                1
45    13          Romelu Lukaku                1
46    13        Scott McTominay                1
47    13               Tim Krul                1
48    13           Tyrone Mings                1
49    13        Victor Lindelöf                1
50    13         William Saliba                1

In [5]:
with pd.ExcelWriter("../data/enriched_matches.xlsx", engine="openpyxl") as writer:
    matches_df.to_excel(writer, sheet_name="Matches", index=False)
    ranking_df.to_excel(writer, sheet_name="Top Scorers", index=False)